"""Alternative-forward-model cohort -- circularity break (Arm 1) + off-model
envelope (Arm 2).

Motivation
----------
The high-D* conditional-coverage wall (Gauge 02/03) was, until now, only ever
demonstrated on cohorts generated by the bi-exponential Eq. (1) -- our synthetic
cohort and the OSIPI DRO. A property of Eq. (1) confirmed only on realizations of
Eq. (1) is circular. There is no in-vivo ground truth, so the only way to break
the circle is ground truth from a DIFFERENT forward model that is NOT
bi-exponential, then ask whether the wall still appears.

Two arms, ONE generator build, kept strictly separate:

* Arm 1 (circularity, 02-3) -- generate ground truth from a genuinely different
  perfusion mechanism (gamma velocity-DISPERSION; ``forward.ivim_signal_dispersion``)
  and RECALIBRATE the conformal predictor WITHIN that distribution (the OSIPI §4.8
  "recalibrated" regime, reused verbatim). Decisive question: does the high-D*eff
  conditional gap PERSIST after within-distribution recalibration? If yes, the wall
  is general (Branch A, circularity broken); if it vanishes, the wall was partly a
  bi-exponential artifact (Branch B). Naive-transfer breaking is expected and is
  NOT the point.

* Arm 2 (envelope, 04-3) -- hold the DEPLOYED bi-exponential-calibrated predictor
  fixed and naive-transfer it across an increasing-deviation family (dispersion CV,
  tri-exp weight, stretched exponent). Report the marginal-coverage degradation
  curve and whether the monitor's AUC tracks the deviation. Coverage breaking is
  the EXPECTED finding; we want the rate and whether the monitor sees it.

D*eff (no literal D* in a dispersion model) is reported CO-PRIMARY under two
surrogates (human sign-off 2026-06-15):
  (A) analytic initial perfusion log-slope = the gamma MEAN ``mu``
      (``forward.dispersion_dstar_eff``) -- model-intrinsic, never references the
      bi-exponential, continuous to the bi-exp limit. The non-circular axis.
  (B) best-fit bi-exponential D* to the (clean) dispersion signal -- the axis a
      bi-exp analyst would see; reported alongside (A) for comparison.

Deterministic from DEFAULT_SEED; reuses gauge.osipi (_calibration_from_osipi /
_evaluate / wall_metric), gauge.invivo.deployed_calibration, and the existing
conformal / monitor / CRLB code unchanged.

Run:  python -m gauge.altmodel              # seed-0 report + figure + provenance
      python -m gauge.altmodel sweep 16     # 16-seed [5,95] bands
"""
import datetime
import json
import os

import numpy as np

from gauge.cohort import DEFAULT_SEED, DEFAULT_SNR_GRID
from gauge.conditional_attack import N_REGIME, _regime_from_true
from gauge.conformal import empirical_coverage
from gauge.baselines import _nlls_init_and_noise
from gauge.forward import (DEFAULT_B_VALUES, ivim_signal_dispersion,
                           ivim_signal_lognormal_dispersion, add_rician_noise,
                           dispersion_crlb_mu_batch, crlb_dstar_batch)
from gauge.robustness import _draw_params, _draw_snr, _simulate
from gauge.invivo import deployed_calibration
from gauge.osipi import (_calibration_from_osipi, _evaluate, wall_metric,
                         ALPHA, NOMINAL, PARAM_NAMES, DSTAR)

# Arm-1 dispersion level: CV = 0.5 (gamma shape k = 4) -- a substantial,
# unambiguously non-bi-exponential perfusion dispersion.
ARM1_CV = 0.5
ARM1_K = 1.0 / (ARM1_CV * ARM1_CV)
GAP_TOL = 0.03                          # under-coverage tol for the Branch verdict

N_TRAIN, N_CAL, N_TEST = 1500, 1200, 1000
N_ARM2 = 1000
# Off-model deviation families (deviation scalar = 0 at exact bi-exponential).
ARM2_FAMILIES = {
    "dispersion": [0.0, 0.2, 0.4, 0.6, 0.8],          # CV
    "triexp":     [0.0, 0.1, 0.2, 0.3, 0.4],          # third-compartment weight g
    "stretched":  [0.0, 0.15, 0.3, 0.45, 0.6],        # |1 - beta|
}
COV_FAIL_TOL = 0.05                     # marginal coverage "fails" below this

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_RESULTS_DIR = os.path.join(_ROOT, "results")
_FIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "figures")
_PAPER_FIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "paper", "figures")
_REPORT = os.path.join(_RESULTS_DIR, "altmodel_report.txt")
_PROVENANCE = os.path.join(_RESULTS_DIR, "altmodel_provenance.json")
_FIG = os.path.join(_FIG_DIR, "altmodel.pdf")
_MULTISEED = os.path.join(_RESULTS_DIR, "altmodel_multiseed.json")
_SURR = ("A", "B")


# --------------------------------------------------------------------------- #
# Cohort generation (dispersion ground truth) + the two D*eff surrogates.
# --------------------------------------------------------------------------- #
def _dispersion_pool(seed, cv, b):
    """One seeded dispersion cohort (D, mu, f) + per-voxel SNR + noisy signals.

    ``params`` columns are (D, mu, f): the gamma-mean ``mu`` IS surrogate-A D*eff.
    At ``cv=0`` the generator is the exact bi-exponential limit (continuity).
    """
    rng = np.random.default_rng(seed + 404)
    n = N_TRAIN + N_CAL + N_TEST
    params = _draw_params(n, rng)                       # (D, D*->mu, f)
    snr = _draw_snr(n, rng, DEFAULT_SNR_GRID)
    sig = _simulate(b, params, snr, rng, model="dispersion", disp_cv=cv)
    return params, snr, sig


def _lognormal_pool(seed, cv, b):
    """A log-normal-kernel dispersion cohort, mirroring :func:`_dispersion_pool`.

    Uses the SAME seeded (D, mu, f) / SNR / noise draws as the gamma pool (rng
    offset ``seed + 404``) and swaps ONLY the dispersion-kernel shape (gamma ->
    log-normal). So the gamma and log-normal Arm-1 cohorts differ in nothing but the
    kernel shape -- an apples-to-apples second confirmation. ``mu`` (column 1) is
    surrogate-A D*eff exactly as in the gamma model.
    """
    rng = np.random.default_rng(seed + 404)
    n = N_TRAIN + N_CAL + N_TEST
    params = _draw_params(n, rng)                       # (D, mu, f)
    snr = _draw_snr(n, rng, DEFAULT_SNR_GRID)
    clean = ivim_signal_lognormal_dispersion(b[None, :], params[:, 0:1],
                                             params[:, 1:2], cv, params[:, 2:3],
                                             S0=1.0)
    sig = add_rician_noise(clean, snr[:, None], rng, S0=1.0)
    return params, snr, sig


def _bestfit_biexp_dstar(params, cv, b):
    """Surrogate B: best-fit bi-exponential D* to the CLEAN dispersion signal.

    Deterministic (no noise) -> a ground-truth-derived stratification axis, not a
    noisy estimate. ``cv=0`` returns mu exactly (clean signal is bi-exponential).
    """
    D, mu, f = params[:, 0], params[:, 1], params[:, 2]
    k = np.inf if cv <= 0 else 1.0 / (cv * cv)
    clean = ivim_signal_dispersion(b[None, :], D[:, None], mu[:, None], k,
                                   f[:, None], S0=1.0)
    theta, _, _ = _nlls_init_and_noise(clean, b)
    return theta[:, 1]


def _split(n):
    a, c = N_TRAIN, N_TRAIN + N_CAL
    idx = np.arange(n)
    return idx[:a], idx[a:c], idx[c:]


# --------------------------------------------------------------------------- #
# The dispersion-model (true-Jacobian) wall metric -- companion to
# osipi.wall_metric (bi-exp Jacobian). Stratified on the mu axis.
# --------------------------------------------------------------------------- #
def wall_metric_dispersion(params, k, b, snr):
    """CRLB(mu) under the TRUE dispersion-model Jacobian vs the mu-tercile width."""
    D, mu, f = params[:, 0], params[:, 1], params[:, 2]
    snr = np.broadcast_to(np.asarray(snr, float), (params.shape[0],))
    kk = np.full(params.shape[0], k, float)
    sd = dispersion_crlb_mu_batch(b, D, mu, kk, f, snr, fix_k=True)
    regime, edges = _regime_from_true(mu)
    bin_edges = np.concatenate([[float(mu.min())], edges, [float(mu.max())]])
    bin_w = np.diff(bin_edges)
    finite = np.isfinite(sd)
    med, ratio = [], []
    for r in range(N_REGIME):
        m = (regime == r) & finite
        mm = float(np.median(sd[m])) if m.any() else np.inf
        med.append(mm)
        ratio.append(mm / bin_w[r])
    abs_growth = (med[-1] / med[0]) if med[0] > 0 else np.inf
    return {"med_crlb": med, "ratio": ratio, "hi_ratio": float(ratio[-1]),
            "abs_growth": float(abs_growth)}


# --------------------------------------------------------------------------- #
# Arm 1 -- one dispersion cohort, evaluated CO-PRIMARY under surrogates A & B.
# Reuses osipi._calibration_from_osipi / _evaluate verbatim (swap only the GT).
# --------------------------------------------------------------------------- #
def run_arm1(seed=DEFAULT_SEED, cv=ARM1_CV, alpha=ALPHA, b=DEFAULT_B_VALUES):
    params, snr, sig = _dispersion_pool(seed, cv, b)
    n = params.shape[0]
    tr, ca, te = _split(n)
    k = np.inf if cv <= 0 else 1.0 / (cv * cv)

    # surrogate ground-truth targets (col 1 = D*eff); D and f are exact.
    dstar_B = _bestfit_biexp_dstar(params, cv, b)
    gt = {"A": params.copy(),
          "B": np.column_stack([params[:, 0], dstar_B, params[:, 2]])}

    snr_levels = list(DEFAULT_SNR_GRID)
    out = {"seed": seed, "cv": cv, "n_test": int(te.size)}
    for s in _SURR:
        g = gt[s]
        test_sig, test_gt, test_snr = sig[te], g[te], snr[te]
        # naive transfer: the deployed bi-exp-calibrated predictor (expected break)
        naive_cal = deployed_calibration(b=b, alpha=alpha, seed=seed)
        naive = _evaluate(naive_cal, test_sig, test_gt, b, test_snr, snr_levels, alpha)
        # recalibrated WITHIN the dispersion distribution (the decisive regime)
        recal_cal = _calibration_from_osipi(sig[tr], g[tr], sig[ca], g[ca],
                                            b, alpha, seed)
        recal = _evaluate(recal_cal, test_sig, test_gt, b, test_snr, snr_levels, alpha)
        out[s] = {"naive": naive, "recal": recal}

    # walls: dispersion-Jacobian (true model, surrogate-A mu axis) + bi-exp-fitted
    # (surrogate-B axis); both reported, labeled by Jacobian (CRLB is secondary).
    out["wall_dispJac"] = wall_metric_dispersion(params[te], k, b, snr[te])
    out["wall_biexpFit"] = wall_metric(gt["B"][te], b, snr[te])
    return out


def run_arm1_lognormal(seed=DEFAULT_SEED, cv=ARM1_CV, alpha=ALPHA, b=DEFAULT_B_VALUES):
    """Arm-1 confirmation under a DIFFERENT dispersion kernel (log-normal).

    Same OSIPI 4.8 naive-transfer + within-distribution recalibration path, same
    non-circular surrogate-A axis (D*eff = kernel mean ``mu``), but the ground truth
    is drawn from a log-normal pseudo-diffusivity kernel instead of gamma. If the
    high-D*eff wall persists here too, the circularity verdict is not specific to the
    gamma parametrisation. Reports surrogate A only (the decisive non-circular axis).
    """
    params, snr, sig = _lognormal_pool(seed, cv, b)
    tr, ca, te = _split(params.shape[0])
    gt = params                                         # col 1 = mu = surrogate-A D*eff
    snr_levels = list(DEFAULT_SNR_GRID)
    test_sig, test_gt, test_snr = sig[te], gt[te], snr[te]
    naive_cal = deployed_calibration(b=b, alpha=alpha, seed=seed)
    naive = _evaluate(naive_cal, test_sig, test_gt, b, test_snr, snr_levels, alpha)
    recal_cal = _calibration_from_osipi(sig[tr], gt[tr], sig[ca], gt[ca], b, alpha, seed)
    recal = _evaluate(recal_cal, test_sig, test_gt, b, test_snr, snr_levels, alpha)
    return {"seed": seed, "cv": cv, "n_test": int(te.size),
            "naive": naive, "recal": recal}


# --------------------------------------------------------------------------- #
# Arm 2 -- deployed bi-exp predictor held FIXED; naive transfer across deviation.
# --------------------------------------------------------------------------- #
def _arm2_test(seed, model, dev, b, fam_idx, step_idx):
    rng = np.random.default_rng(seed + 700 + 31 * fam_idx + step_idx)
    params = _draw_params(N_ARM2, rng)
    snr = _draw_snr(N_ARM2, rng, DEFAULT_SNR_GRID)
    if model == "dispersion":
        sig = _simulate(b, params, snr, rng, model="dispersion", disp_cv=dev)
    elif model == "triexp":
        sig = _simulate(b, params, snr, rng, model="triexp", triexp=(4.0, dev))
    elif model == "stretched":
        sig = _simulate(b, params, snr, rng, model="stretched", beta=1.0 - dev)
    else:
        raise ValueError(model)
    return params, snr, sig          # params = nominal (D, D*, f) coverage target


def run_arm2(seed=DEFAULT_SEED, alpha=ALPHA, b=DEFAULT_B_VALUES):
    """Fixed deployed bi-exp calibration, naive-transferred across each family."""
    cal = deployed_calibration(b=b, alpha=alpha, seed=seed)
    fams = {}
    for fi, (model, devs) in enumerate(ARM2_FAMILIES.items()):
        rows = []
        for si, dev in enumerate(devs):
            params, snr, sig = _arm2_test(seed, model, dev, b, fi, si)
            ev = _evaluate(cal, sig, params, b, snr, None, alpha)
            rows.append({"dev": float(dev),
                         "cqr_marg": ev["cqr_marg"], "split_marg": ev["split_marg"],
                         "monitor_auc": ev["monitor_auc"],
                         "monitor_fires": bool(ev["monitor_fires"])})
        fams[model] = rows
    return fams


# --------------------------------------------------------------------------- #
# Flat scalar dict for the multi-seed band harness + consistency gate.
# --------------------------------------------------------------------------- #
def compute_all(seed=DEFAULT_SEED):
    out = {}
    payload = {}
    arm1 = run_arm1(seed=seed)
    payload["arm1"] = arm1
    for s in _SURR:
        for cal in ("naive", "recal"):
            ev = arm1[s][cal]
            for j, nm in enumerate(PARAM_NAMES):
                out[f"altmodel/arm1/{s}/{cal}/cqr_marg/{nm}"] = float(ev["cqr_marg"][j])
            out[f"altmodel/arm1/{s}/{cal}/cqr_hiDstar"] = float(ev["cqr_terc"][-1])
            out[f"altmodel/arm1/{s}/{cal}/cqr_loDstar"] = float(ev["cqr_terc"][0])
        out[f"altmodel/arm1/{s}/naive/monitor_auc"] = float(arm1[s]["naive"]["monitor_auc"])
        out[f"altmodel/arm1/{s}/naive/monitor_fires"] = float(arm1[s]["naive"]["monitor_fires"])
    for tag, wkey in (("dispJac", "wall_dispJac"), ("biexpFit", "wall_biexpFit")):
        w = arm1[wkey]
        for i, kk in enumerate(("lo", "mid", "hi")):
            out[f"altmodel/arm1/wall_{tag}/crlb_over_width/{kk}"] = float(w["ratio"][i])
        out[f"altmodel/arm1/wall_{tag}/abs_growth"] = float(w["abs_growth"])

    # Arm-1 confirmation under a SECOND, independent dispersion kernel (log-normal)
    # on the non-circular surrogate-A axis: does the wall persist under a different
    # kernel shape? (Branch-A robustness to the dispersion parametrisation.)
    arm1_ln = run_arm1_lognormal(seed=seed)
    payload["arm1_lognormal"] = arm1_ln
    for cal in ("naive", "recal"):
        ev = arm1_ln[cal]
        for j, nm in enumerate(PARAM_NAMES):
            out[f"altmodel/arm1_lognormal/A/{cal}/cqr_marg/{nm}"] = float(ev["cqr_marg"][j])
    for kk, idx in (("lo", 0), ("mid", 1), ("hi", 2)):
        out[f"altmodel/arm1_lognormal/A/recal/cqr_{kk}Dstar"] = float(arm1_ln["recal"]["cqr_terc"][idx])
    out["altmodel/arm1_lognormal/A/naive/monitor_auc"] = float(arm1_ln["naive"]["monitor_auc"])

    arm2 = run_arm2(seed=seed)
    payload["arm2"] = arm2
    for model, rows in arm2.items():
        for si, r in enumerate(rows):
            for j, nm in enumerate(PARAM_NAMES):
                out[f"altmodel/arm2/{model}/dev{si}/cov/{nm}"] = float(r["cqr_marg"][j])
            out[f"altmodel/arm2/{model}/dev{si}/auc"] = float(r["monitor_auc"])
            out[f"altmodel/arm2/{model}/dev{si}/fires"] = float(r["monitor_fires"])

    # continuity gate (Checkpoint 3 sanity): cv=0 dispersion == bi-exp control.
    cont = continuity_gate(seed=seed)
    payload["continuity"] = cont
    out["altmodel/continuity/gen_max_abs_err"] = float(cont["gen_max_abs_err"])
    out["altmodel/continuity/cv0_recal_hiDstar_A"] = float(cont["cv0_recal_hiDstar_A"])
    return out, payload


# --------------------------------------------------------------------------- #
# Continuity gate: the dispersion generator at CV=0 must reproduce the
# bi-exponential cohort to numerical tolerance, and Arm 1 at CV=0 must reproduce
# the bi-exp control's recalibrated high-D* number.
# --------------------------------------------------------------------------- #
def continuity_gate(seed=DEFAULT_SEED, b=DEFAULT_B_VALUES):
    from gauge.forward import ivim_signal
    rng = np.random.default_rng(seed + 909)
    params = _draw_params(400, rng)
    D, mu, f = params[:, 0], params[:, 1], params[:, 2]
    clean_disp = ivim_signal_dispersion(b[None, :], D[:, None], mu[:, None],
                                        np.inf, f[:, None], S0=1.0)
    clean_biexp = ivim_signal(b[None, :], D[:, None], mu[:, None], f[:, None], S0=1.0)
    gen_max_abs_err = float(np.max(np.abs(clean_disp - clean_biexp)))
    # Arm 1 at the bi-exp limit (cv=0) -- surrogate A recal high-D* tercile.
    a1_cv0 = run_arm1(seed=seed, cv=0.0)
    cv0_hi_A = float(a1_cv0["A"]["recal"]["cqr_terc"][-1])
    return {"gen_max_abs_err": gen_max_abs_err,
            "cv0_recal_hiDstar_A": cv0_hi_A,
            "cv0_recal_terc_A": [float(x) for x in a1_cv0["A"]["recal"]["cqr_terc"]]}


# --------------------------------------------------------------------------- #
# Verdict + report
# --------------------------------------------------------------------------- #
def _fmt(a):
    return "[" + ", ".join(f"{v:.3f}" for v in a) + "]"


def _verdict(arm1):
    """Branch A (wall general) vs Branch B (bi-exp specific), driven by the
    non-circular surrogate A; surrogate B reported alongside for concordance."""
    recal_hi_A = float(arm1["A"]["recal"]["cqr_terc"][-1])
    recal_hi_B = float(arm1["B"]["recal"]["cqr_terc"][-1])
    gap_A = NOMINAL - recal_hi_A
    gap_B = NOMINAL - recal_hi_B
    persists_A = gap_A >= GAP_TOL
    persists_B = gap_B >= GAP_TOL
    if persists_A:
        branch = "A"
        text = ("BRANCH A -- WALL IS GENERAL / CIRCULARITY BROKEN: the high-D*eff "
                "conditional gap PERSISTS after within-distribution recalibration on "
                "the non-bi-exponential dispersion ground truth "
                f"(surrogate A recal hi-D*eff = {recal_hi_A:.3f}, gap {gap_A:+.3f} vs "
                f"nominal {NOMINAL:.2f}). The wall is a property of perfusion "
                "estimation, not of Eq. (1).")
    else:
        branch = "B"
        text = ("BRANCH B -- WALL IS BI-EXPONENTIAL-SPECIFIC: the high-D*eff gap "
                "VANISHES after recalibration on the dispersion ground truth "
                f"(surrogate A recal hi-D*eff = {recal_hi_A:.3f}, gap {gap_A:+.3f}). "
                "The claim must stay scoped to the bi-exponential model class.")
    return {"branch": branch, "text": text,
            "recal_hi_A": recal_hi_A, "recal_hi_B": recal_hi_B,
            "gap_A": gap_A, "gap_B": gap_B,
            "persists_A": persists_A, "persists_B": persists_B}


def main(seed=DEFAULT_SEED):
    out, payload = compute_all(seed=seed)
    arm1, arm2, cont = payload["arm1"], payload["arm2"], payload["continuity"]
    arm1_ln = payload["arm1_lognormal"]
    v = _verdict(arm1)
    lines = []
    def w(s=""): lines.append(s)

    w("=" * 96)
    w("GAUGE -- ALTERNATIVE-FORWARD-MODEL COHORT (circularity break + off-model envelope)")
    w("=" * 96)
    w(f"seed={seed}; nominal coverage {NOMINAL:.2f}; alpha={ALPHA}.")
    w("Ground truth from a GENUINELY non-bi-exponential mechanism: gamma velocity-")
    w(f"DISPERSION perfusion (CV={ARM1_CV}, gamma shape k={ARM1_K:.1f}); NOT a "
      "realization of Eq. (1).")
    w("D*eff reported CO-PRIMARY: (A) analytic perfusion log-slope = gamma mean mu "
      "(non-circular);")
    w("(B) best-fit bi-exponential D* to the clean dispersion signal.")
    w("")

    # ---- Arm 1 ------------------------------------------------------------- #
    w("-" * 96)
    w("ARM 1 -- CIRCULARITY: within-distribution recalibration on dispersion truth "
      "(OSIPI 4.8 harness)")
    w("-" * 96)
    for s in _SURR:
        naive, recal = arm1[s]["naive"], arm1[s]["recal"]
        w(f"  [surrogate {s}]  D*eff = "
          + ("gamma mean mu (analytic log-slope)" if s == "A"
             else "best-fit bi-exp D*"))
        w(f"    naive-transfer  CQR marginal (D, D*eff, f) = {_fmt(naive['cqr_marg'])}")
        w(f"    recalibrated    CQR marginal (D, D*eff, f) = {_fmt(recal['cqr_marg'])}  "
          f"vs nominal {NOMINAL:.2f}")
        w(f"    recalibrated CQR coverage by true-D*eff tercile [lo, mid, hi] = "
          f"{_fmt(recal['cqr_terc'])}")
        mf = "FIRES" if naive["monitor_fires"] else "does NOT fire"
        w(f"    naive-transfer deployment monitor: {mf} (AUC={naive['monitor_auc']:.2f})")
        w("")
    wd, wb = arm1["wall_dispJac"], arm1["wall_biexpFit"]
    w(f"  wall (CRLB/tercile-width [lo, mid, hi]):")
    w(f"    dispersion-Jacobian (TRUE model, mu axis) = {_fmt(wd['ratio'])}; "
      f"abs-CRLB growth {wd['abs_growth']:.1f}x")
    w(f"    bi-exp-fitted Jacobian (surrogate-B axis)  = {_fmt(wb['ratio'])}; "
      f"abs-CRLB growth {wb['abs_growth']:.1f}x")
    w("    (CRLB is SECONDARY and labeled by Jacobian; the conditional-coverage "
      "persistence above is the primary, CRLB-independent circularity-breaker.)")
    w("")
    w("  CONTINUITY GATE (Checkpoint-3 sanity): dispersion generator at CV=0 "
      "reproduces the")
    w(f"    bi-exponential cohort: max |S_disp(CV=0) - S_biexp| = "
      f"{cont['gen_max_abs_err']:.2e} (numerically exact);")
    w(f"    Arm-1 CV=0 recalibrated high-D* tercile coverage = "
      f"{cont['cv0_recal_hiDstar_A']:.3f} (the bi-exp-limit control; "
      f"terciles {_fmt(cont['cv0_recal_terc_A'])}).")
    w("")
    w("  >>> ARM 1 VERDICT")
    w(f"      {v['text']}")
    w(f"      concordance: surrogate A recal hi-D*eff {v['recal_hi_A']:.3f} "
      f"(gap {v['gap_A']:+.3f}); surrogate B {v['recal_hi_B']:.3f} "
      f"(gap {v['gap_B']:+.3f}); "
      f"Branch-A persists A={v['persists_A']} / B={v['persists_B']}.")
    w("")

    # ---- Arm 1 confirmation: SECOND kernel shape (log-normal) --------------- #
    ln_terc = arm1_ln["recal"]["cqr_terc"]
    ln_hi = float(ln_terc[-1])
    ln_persists = (NOMINAL - ln_hi) >= GAP_TOL
    w("  SECOND-KERNEL CONFIRMATION (log-normal dispersion, same CV, surrogate-A "
      "axis): the wall is")
    w("  not specific to the gamma parametrisation --")
    w(f"    log-normal recalibrated CQR coverage by D*eff tercile [lo, mid, hi] = "
      f"{_fmt(ln_terc)}")
    w(f"    log-normal recal hi-D*eff = {ln_hi:.3f} (gap {NOMINAL - ln_hi:+.3f} vs "
      f"nominal {NOMINAL:.2f}); Branch-A persists = {ln_persists}")
    w(f"    log-normal naive-transfer monitor AUC = {arm1_ln['naive']['monitor_auc']:.2f}")
    w("")

    # ---- Arm 2 ------------------------------------------------------------- #
    w("-" * 96)
    w("ARM 2 -- ENVELOPE: deployed bi-exp calibration, naive transfer across "
      "increasing deviation")
    w("-" * 96)
    for model, rows in arm2.items():
        scalar = {"dispersion": "CV", "triexp": "g", "stretched": "|1-beta|"}[model]
        w(f"  [{model}] deviation scalar = {scalar} (0 = exact bi-exponential):")
        w(f"    {'dev':>6} | {'cov D':>7} | {'cov D*':>7} | {'cov f':>7} | "
          f"{'monitor AUC':>11} | {'fires':>6}")
        cov_fail_dev, fire_dev = None, None
        for r in rows:
            cmin = float(np.min(r["cqr_marg"]))
            failed = cmin < NOMINAL - COV_FAIL_TOL
            if failed and cov_fail_dev is None:
                cov_fail_dev = r["dev"]
            if r["monitor_fires"] and fire_dev is None:
                fire_dev = r["dev"]
            w(f"    {r['dev']:>6.2f} | {r['cqr_marg'][0]:>7.3f} | "
              f"{r['cqr_marg'][1]:>7.3f} | {r['cqr_marg'][2]:>7.3f} | "
              f"{r['monitor_auc']:>11.2f} | "
              f"{('YES' if r['monitor_fires'] else 'no'):>6}")
        rec = rows[0]["cqr_marg"]
        recovered = bool(np.max(np.abs(np.asarray(rec) - NOMINAL)) <= COV_FAIL_TOL)
        before = (fire_dev is not None and
                  (cov_fail_dev is None or fire_dev <= cov_fail_dev))
        w(f"    zero-deviation recovery: dev=0 coverage {_fmt(rec)} "
          f"(within {COV_FAIL_TOL} of nominal: {recovered}).")
        w(f"    monitor first fires at dev={fire_dev}; marginal coverage first "
          f"fails at dev={cov_fail_dev}; fires-before-failure: "
          f"{'YES' if before else 'NO'}.")
        w("")

    w("=" * 96)
    w(f"HEADLINE: Arm-1 Branch {v['branch']} (circularity "
      f"{'broken -- wall general' if v['branch']=='A' else 'wall bi-exp-specific'}); "
      f"continuity gate gen-err {cont['gen_max_abs_err']:.1e}.")
    w(f"SECOND-KERNEL CONFIRMATION (log-normal): Branch-A persists = {ln_persists} "
      f"(recal hi-D*eff {ln_hi:.3f}).")
    w("=" * 96)

    os.makedirs(_RESULTS_DIR, exist_ok=True)
    with open(_REPORT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\n[altmodel] wrote report -> {_REPORT}")
    _write_provenance(seed, payload, v)
    _make_figure(payload, v)
    return 0


def _write_provenance(seed, payload, v):
    arm1, arm2, cont = payload["arm1"], payload["arm2"], payload["continuity"]
    run = {
        "seed": seed, "alpha": ALPHA, "nominal_coverage": NOMINAL,
        "mechanism": "gamma velocity-dispersion perfusion (non-bi-exponential)",
        "arm1_cv": ARM1_CV, "arm1_gamma_k": ARM1_K,
        "dstar_eff_surrogates": {"A": "analytic perfusion log-slope = gamma mean mu",
                                 "B": "best-fit bi-exp D* to clean dispersion signal"},
        "arm1_verdict_branch": v["branch"], "arm1_verdict_text": v["text"],
        "arm1": {s: {"naive_cqr_marg": [float(x) for x in arm1[s]["naive"]["cqr_marg"]],
                     "recal_cqr_marg": [float(x) for x in arm1[s]["recal"]["cqr_marg"]],
                     "recal_cqr_tercile_lo_mid_hi": [float(x) for x in arm1[s]["recal"]["cqr_terc"]],
                     "naive_monitor_fires": bool(arm1[s]["naive"]["monitor_fires"]),
                     "naive_monitor_auc": float(arm1[s]["naive"]["monitor_auc"])}
                 for s in _SURR},
        "arm1_wall_dispersion_jacobian": [float(x) for x in arm1["wall_dispJac"]["ratio"]],
        "arm1_wall_biexp_fitted_jacobian": [float(x) for x in arm1["wall_biexpFit"]["ratio"]],
        "arm1_lognormal_confirmation": {
            "kernel": "log-normal dispersion (mean=mu, CV=ARM1_CV), surrogate-A axis",
            "recal_cqr_marg": [float(x) for x in payload["arm1_lognormal"]["recal"]["cqr_marg"]],
            "recal_cqr_tercile_lo_mid_hi": [float(x) for x in payload["arm1_lognormal"]["recal"]["cqr_terc"]],
            "naive_monitor_auc": float(payload["arm1_lognormal"]["naive"]["monitor_auc"])},
        "continuity_gen_max_abs_err": cont["gen_max_abs_err"],
        "continuity_cv0_recal_hiDstar_A": cont["cv0_recal_hiDstar_A"],
        "arm2": {model: [{"dev": r["dev"],
                          "cqr_marg": [float(x) for x in r["cqr_marg"]],
                          "monitor_auc": float(r["monitor_auc"]),
                          "monitor_fires": bool(r["monitor_fires"])} for r in rows]
                 for model, rows in arm2.items()},
        "computed_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    }
    prov = {}
    if os.path.exists(_PROVENANCE):
        try:
            prov = json.load(open(_PROVENANCE))
        except Exception:
            prov = {}
    prov["run"] = run
    os.makedirs(_RESULTS_DIR, exist_ok=True)
    with open(_PROVENANCE, "w") as fh:
        json.dump(prov, fh, indent=1)
    print(f"[altmodel] wrote provenance -> {_PROVENANCE}")


def _make_figure(payload, v):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as e:                                  # pragma: no cover
        print(f"[altmodel figures] skipped ({e})")
        return
    arm1, arm2 = payload["arm1"], payload["arm2"]
    fig, ax = plt.subplots(1, 3, figsize=(14.0, 4.2))
    t = np.arange(3)

    # Panel A -- Arm 1 conditional coverage by D*eff tercile (recal), A vs B.
    ax[0].plot(t, arm1["A"]["recal"]["cqr_terc"], "o-", c="#2c7fb8",
               label="surrogate A (mu)")
    ax[0].plot(t, arm1["B"]["recal"]["cqr_terc"], "s--", c="#756bb1",
               label="surrogate B (bi-exp fit)")
    ax[0].plot(t, arm1["A"]["naive"]["cqr_terc"], "o:", c="#c0392b", alpha=0.6,
               label="naive transfer (A)")
    ax[0].axhline(NOMINAL, ls="--", c="k", lw=1)
    ax[0].set_xticks(t); ax[0].set_xticklabels(["lo", "mid", "hi"])
    ax[0].set_ylim(0.4, 1.02); ax[0].set_ylabel("conditional coverage")
    ax[0].set_title(f"(A) Arm 1: D*eff-tercile coverage\non DISPERSION truth "
                    f"(Branch {v['branch']})")
    ax[0].legend(fontsize=7, loc="lower left")

    # Panel B -- Arm 2 marginal D* degradation vs deviation, per family.
    cols = {"dispersion": "#16a085", "triexp": "#e67e22", "stretched": "#8e44ad"}
    for model, rows in arm2.items():
        devs = [r["dev"] for r in rows]
        covd = [r["cqr_marg"][DSTAR] for r in rows]
        ax[1].plot(devs, covd, "o-", c=cols[model], label=model)
    ax[1].axhline(NOMINAL, ls="--", c="k", lw=1, label=f"nominal {NOMINAL:.2f}")
    ax[1].axhline(NOMINAL - COV_FAIL_TOL, ls=":", c="#c0392b", lw=1)
    ax[1].set_xlabel("deviation from bi-exponential")
    ax[1].set_ylabel("marginal D* coverage")
    ax[1].set_title("(B) Arm 2: coverage degradation curve")
    ax[1].legend(fontsize=7, loc="lower left")

    # Panel C -- Arm 2 monitor AUC vs deviation.
    for model, rows in arm2.items():
        devs = [r["dev"] for r in rows]
        auc = [r["monitor_auc"] for r in rows]
        ax[2].plot(devs, auc, "o-", c=cols[model], label=model)
    ax[2].axhline(0.5, ls=":", c="0.5", lw=1)
    ax[2].set_xlabel("deviation from bi-exponential")
    ax[2].set_ylabel("monitor AUC (cal vs deviated)")
    ax[2].set_ylim(0.4, 1.02)
    ax[2].set_title("(C) Arm 2: monitor tracks off-model drift")
    ax[2].legend(fontsize=7, loc="lower right")

    fig.suptitle("Alternative forward model: circularity break (Arm 1) + "
                 "off-model envelope (Arm 2)", fontsize=10)
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    for d in (_FIG_DIR, _PAPER_FIG_DIR):
        os.makedirs(d, exist_ok=True)
        fig.savefig(os.path.join(d, "altmodel.pdf"), bbox_inches="tight")
    plt.close(fig)
    print(f"[altmodel figures] wrote altmodel.pdf -> {_FIG_DIR} and {_PAPER_FIG_DIR}")


# --------------------------------------------------------------------------- #
# Multi-seed band sweep -- reuses multiseed.seed_list + _agg_scalar (point =
# across-seed mean, [5,95] band), exactly like gauge.osipi.sweep.
# --------------------------------------------------------------------------- #
def _seed_path(seed):
    return os.path.join(_RESULTS_DIR, "altmodel_seeds", f"{int(seed)}.json")


def sweep(n=16, force=False, verbose=True):
    from gauge.multiseed import seed_list, _agg_scalar
    seeds = seed_list(n)
    os.makedirs(os.path.join(_RESULTS_DIR, "altmodel_seeds"), exist_ok=True)
    for s in seeds:
        p = _seed_path(s)
        if (not force) and os.path.exists(p):
            if verbose:
                print(f"[altmodel sweep] seed {s} present -- skip")
            continue
        flat, _ = compute_all(seed=s)
        with open(p, "w") as fh:
            json.dump({"seed": int(s), "flat": flat}, fh)
        if verbose:
            print(f"[altmodel sweep] seed {s} done")
    recs = [json.load(open(_seed_path(s))) for s in seeds if os.path.exists(_seed_path(s))]
    seed0 = next(r for r in recs if r["seed"] == DEFAULT_SEED)
    items = {}
    for k in sorted(seed0["flat"].keys()):
        vals = [r["flat"][k] for r in recs if k in r["flat"]]
        items[k] = _agg_scalar(vals, k, seed0["flat"][k])
    out = {"n_seeds": len(recs), "seeds": [r["seed"] for r in recs],
           "alpha": ALPHA, "items": items}
    with open(_MULTISEED, "w") as fh:
        json.dump(out, fh, indent=2)
    if verbose:
        print(f"[altmodel sweep] aggregated {len(recs)} seeds -> {_MULTISEED}")
    return out


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "sweep":
        nn = int(sys.argv[2]) if len(sys.argv) > 2 else 16
        sweep(n=nn, force=os.environ.get("GAUGE_FORCE") == "1")
        raise SystemExit(0)
    sd = int(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SEED
    raise SystemExit(main(seed=sd))
