"""CP4 consistency gate -- every data number in minos.tex traces to a seeded printout.

Single source of truth for the manuscript's numbers:
  1. load the seeded applied results (../results/RESULTS_CP2.json, RESULTS_CP3.json);
  2. carry the theory constants verbatim from the machine-checked theory gates
     (Minos/theory: gap_scaling.py / detectability.py / confirm.py -- see plumbline.md);
  3. emit numbers.tex with one \newcommand per number (the ONLY place minos.tex gets a value);
  4. verify minos.tex references only macros that numbers.tex defines (so no untraceable
     magic number can appear in the prose), and run a few internal-consistency asserts.

Theory constants are PINNED (not Fashion/Gauge-dependent -> SOLID). Applied numbers are
PROVISIONAL (Fashion/Gauge-dependent). Run:
  proteus/bin/python Minos/future/paper/consistency.py        # writes numbers.tex + checks
Exit 0 = gate green.
"""
from __future__ import annotations

import json
import os
import re
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(os.path.dirname(HERE), "results")
TEX = os.path.join(HERE, "minos.tex")
NUMBERS_TEX = os.path.join(HERE, "numbers.tex")


def _load(name):
    with open(os.path.join(RESULTS, name)) as fh:
        return json.load(fh)


def build_numbers():
    cp2 = _load("RESULTS_CP2.json")
    cp3 = _load("RESULTS_CP3.json")

    # ---- theory constants: from the machine-checked theory gates (SOLID, not provisional) ----
    nums = {
        # source: theory/gap_scaling.py (GATE 1) + plumbline.md confirmation table
        "TauStarLead": ("1.0485", "theory GATE1: leading-order tau* at default cell"),
        "Gfull": ("0.0847", "theory GATE3: full-theory gap at default cell"),
        "GleadSlope": ("0.0727", "theory GATE1: |z*(3)|/6 leading slope"),
        "ZstarThree": ("-0.436", "theory GATE1: z*(lambda=3)"),
        "ObsAUC": ("1.00", "theory GATE3 / v3: observable detection AUC"),
        "HiddenAUC": ("0.50", "theory GATE2-3 / Thm 2(i): hidden detection AUC"),
        "LU": ("3.0", "theory GATE2: Lipschitz constant L_U=k_under"),
    }

    # ---- applied CP2 (PROVISIONAL) ----
    cells = cp2["cells"]
    asym = [c for c in cells if c["lam"] > 1.0 and np.isfinite(c["G_std"])]
    mean_tau_stat = float(np.nanmean([c["tau_stat"] for c in asym]))
    mean_std_u = float(np.nanmean([c["std_u"] for c in asym]))
    skewed = [c for c in asym if abs(c["gamma"]) > 0.3 and abs(c["G_theory"]) > 1e-3]
    ratios = [abs(c["G_std"]) / abs(c["G_theory"]) for c in skewed]
    med_ratio = float(np.median(ratios)) if ratios else float("nan")
    max_regret = float(np.nanmax([c["regret_coverage_cal"] for c in cells
                                  if np.isfinite(c["regret_coverage_cal"])]))
    sign_ok = sum(1 for c in asym if c["sign_match_std"])
    nums.update({
        "MeanTauStat": (f"{mean_tau_stat:.2f}", "CP2: mean tau_stat over lambda>1 cells"),
        "MeanStdU": (f"{mean_std_u:.2f}", "CP2: mean std(u)"),
        "GstdRatio": (f"{med_ratio:.0f}", "CP2: median |G_std/G_theory|, |gamma|>0.3"),
        "MaxRegret": (f"{max_regret:.1f}", "CP2: max coverage-cal regret (utility units)"),
        "SignOk": (f"{sign_ok}", "CP2: cells where G_std sign matches theory"),
        "NAsym": (f"{len(asym)}", "CP2: asymmetric-cost cells analysed"),
    })

    # ---- applied CP3 (PROVISIONAL) ----
    r = cp3["results"]
    def auc(k):
        return f"{r[k]['auc']:.2f}"
    nums.update({
        "SnrAUC": (auc("snr_drop_40to12"), "CP3: observable SNR-shift AUC"),
        "DshiftAUC": (auc("D_shift_up"), "CP3: observable D-shift AUC"),
        "FshiftAUC": (auc("f_shift_up"), "CP3: observable f-shift AUC"),
        "TriexpAUC": (auc("triexp_perfusion_misspec"), "CP3: wall-adjacent tri-exp AUC"),
        "HiddenTestAUC": (auc("hidden_exchangeable"), "CP3: hidden exchangeable AUC"),
        "MargCov": (f"{r['hidden_exchangeable']['marginal_coverage']:.2f}",
                    "CP3: marginal D* coverage (hidden test)"),
        "HiDstarCov": (f"{r['hidden_exchangeable']['high_dstar_coverage']:.2f}",
                       "CP3: high-D* tercile coverage (hidden test)"),
    })
    return nums


def write_numbers(nums):
    lines = ["% AUTO-GENERATED by consistency.py from seeded results -- DO NOT EDIT BY HAND.",
             "% Theory macros are SOLID; applied (CP2/CP3) macros are PROVISIONAL.", ""]
    for key, (val, src) in nums.items():
        lines.append(f"\\newcommand{{\\num{key}}}{{{val}}}  % {src}")
    with open(NUMBERS_TEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def verify_tex(nums):
    if not os.path.exists(TEX):
        print(f"  [skip] {TEX} not present yet"); return True
    with open(TEX) as fh:
        tex = fh.read()
    used = set(re.findall(r"\\num([A-Za-z]+)\b", tex))
    defined = set(nums)
    undefined = used - defined
    ok = not undefined
    print(f"  macros used in minos.tex: {len(used)}; defined: {len(defined)}; "
          f"undefined: {sorted(undefined) if undefined else 'none'}")
    # internal consistency: ratio must be >1 (the honest CP2 mismatch) and hidden AUC near 0.5
    asserts = []
    asserts.append(("CP2 ratio>1 (quant law misses)", float(nums["GstdRatio"][0]) > 1))
    asserts.append(("CP3 hidden AUC<0.65 (blind)", float(nums["HiddenTestAUC"][0]) < 0.65))
    asserts.append(("CP3 SNR AUC>0.9 (observable)", float(nums["SnrAUC"][0]) > 0.9))
    for name, cond in asserts:
        print(f"  assert {name}: {'PASS' if cond else 'FAIL'}")
        ok = ok and cond
    return ok


def main():
    print("CP4 consistency gate -- numbers.tex from seeded results; minos.tex traceability")
    nums = build_numbers()
    write_numbers(nums)
    print(f"  wrote {NUMBERS_TEX} ({len(nums)} numbers)")
    ok = verify_tex(nums)
    if ok:
        print("\nCP4 CONSISTENCY: PASS")
        return 0
    print("\nCP4 CONSISTENCY: FAIL")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
