#!/usr/bin/env python
"""CP4-style traceability gate for the Lethe manuscript (Echo portion).

Regenerates ``numbers.tex`` from the seeded result printouts (``results/RESULTS_VALIDATION.json``
= PROVISIONAL real-data verdict; ``results/RESULTS_HARNESS.json`` = SOLID method self-test), then
verifies that every ``\\num*`` macro used in ``lethe.tex`` is defined and that the manuscript's
load-bearing claims hold internally. Run: ``python paper/consistency.py`` (exit 0 = gate PASS).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULTS = HERE.parent / "results"
TEX = HERE / "lethe.tex"
NUMBERS = HERE / "numbers.tex"


def _load(name):
    return json.loads((RESULTS / name).read_text())


def build_numbers():
    val = _load("RESULTS_VALIDATION.json")
    har = _load("RESULTS_HARNESS.json")["checks"]
    hD = val["headline"]["D"]; hDs = val["headline"]["Dstar"]; hF = val["headline"]["f"]
    sw = val["sensitivity_single_voxel_snr"]
    gb = val["gauge_baseline"]
    st = har["scaled_recovers_analytic"]; bi = har["bias_invariance"]; dg = har["distinct_from_gauge"]

    nums = {
        # --- PROVISIONAL real-data verdict (Echo portion) ---
        "N": (f"{val['n']}", "test-retest tumors (ACRIN-6698)"),
        "Target": (f"{val['analytic_repeat_target']:.3f}", "analytic repeat-coverage target"),
        "HeadSNR": (f"{val['headline_single_voxel_snr']:.0f}", "headline single-voxel SNR"),
        "CovD": (f"{hD['coverage']:.3f}", "coverage(D)"),
        "CovDlo": (f"{hD['coverage_ci'][0]:.3f}", "coverage(D) BCa lo"),
        "CovDhi": (f"{hD['coverage_ci'][1]:.3f}", "coverage(D) BCa hi"),
        "RD": (f"{hD['scale_ratio_R']:.3f}", "scale ratio R(D)"),
        "Zdisp": (f"{hD['z_dispersion']:.2f}", "z-dispersion(D)"),
        "SigImpl": (f"{hD['sigma_implied']*1e4:.2f}", "sigma_implied(D) x1e4 mm2/s"),
        "SigRep": (f"{hD['sigma_repeat']*1e4:.2f}", "sigma_repeat(D) x1e4 mm2/s"),
        "CovDstar": (f"{hDs['coverage']:.3f}", "coverage(D*)"),
        "RDstar": (f"{hDs['scale_ratio_R']:.1f}", "scale ratio R(D*)"),
        "CovF": (f"{hF['coverage']:.3f}", "coverage(f)"),
        "RF": (f"{hF['scale_ratio_R']:.3f}", "scale ratio R(f)"),
        "CovSNRten": (f"{sw['10.0']['D']:.3f}", "coverage(D) at single-voxel SNR 10"),
        "CovSNRhund": (f"{sw['100.0']['D']:.3f}", "coverage(D) at single-voxel SNR 100"),
        # --- Gauge baseline (cited) ---
        "GaugeR": (f"{gb['D_spearman']:.2f}", "Gauge D width-repeatability Spearman"),
        "GaugeRlo": (f"{gb['D_ci'][0]:.2f}", "Gauge D Spearman CI lo"),
        "GaugeRhi": (f"{gb['D_ci'][1]:.2f}", "Gauge D Spearman CI hi"),
        "GaugeDstar": (f"{gb['Dstar_spearman']:.2f}", "Gauge D* Spearman (null)"),
        # --- SOLID method self-test ---
        "SelfScaled": (f"{st['value']:.3f}", "self-test: scaled coverage"),
        "SelfTarget": (f"{st['target']:.3f}", "self-test: analytic target"),
        "SelfBias": (f"{bi['value']:.3f}", "self-test: bias-invariant coverage"),
        "SpearBefore": (f"{dg['spearman_before']:.3f}", "self-test: Spearman before rescale"),
        "SpearAfter": (f"{dg['spearman_after_rescale']:.3f}", "self-test: Spearman after rescale"),
        "CovRescBefore": (f"{dg['coverage_before']:.3f}", "self-test: coverage before rescale"),
        "CovRescAfter": (f"{dg['coverage_after_rescale']:.3f}", "self-test: coverage after rescale"),
    }
    return nums, val, har


def write_numbers(nums):
    lines = ["% AUTO-GENERATED by consistency.py from seeded results -- DO NOT EDIT BY HAND.",
             "% Real-data (Echo-portion) macros are PROVISIONAL (Fashion/Gauge/Minos in review);",
             "% method self-test macros are SOLID.", ""]
    for k, (v, why) in nums.items():
        lines.append(f"\\newcommand{{\\num{k}}}{{{v}}}  % {why}")
    NUMBERS.write_text("\n".join(lines) + "\n")


def verify(nums, val, har):
    ok = True
    # 1. every \num* in the tex is defined
    if TEX.exists():
        used = set(re.findall(r"\\num([A-Za-z]+)\b", TEX.read_text()))
        undefined = used - set(nums)
        print(f"  macros used={len(used)} defined={len(nums)} undefined={sorted(undefined)}")
        if undefined:
            ok = False
    else:
        print("  (lethe.tex absent -- numbers.tex generated; skipping macro cross-check)")
    # 2. load-bearing internal-consistency asserts
    hD = val["headline"]["D"]
    asserts = [
        ("verdict == LETHE", val["gate"]["VERDICT"] == "LETHE"),
        ("coverage(D) under-scaled (<0.65)", hD["coverage"] < 0.65),
        ("R(D) < 1 (interval narrower than repeatability)", hD["scale_ratio_R"] < 1.0),
        ("under-scaled across grid (SNR10 D < 0.65)", val["sensitivity_single_voxel_snr"]["10.0"]["D"] < 0.65),
        ("self-test ALL_PASS", har["ALL_PASS"]),
        ("distinct: Spearman invariant to rescale",
         abs(har["distinct_from_gauge"]["spearman_before"]
             - har["distinct_from_gauge"]["spearman_after_rescale"]) < 1e-9),
        ("distinct: coverage moves under rescale",
         abs(har["distinct_from_gauge"]["coverage_before"]
             - har["distinct_from_gauge"]["coverage_after_rescale"]) > 0.05),
    ]
    for name, cond in asserts:
        print(f"  assert {name}: {'PASS' if cond else 'FAIL'}")
        ok = ok and bool(cond)
    return ok


def main():
    nums, val, har = build_numbers()
    write_numbers(nums)
    print(f"wrote {NUMBERS} ({len(nums)} macros)")
    ok = verify(nums, val, har)
    print("CP4 consistency gate:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
