#!/usr/bin/env python3
"""CP4 consistency gate for the Augur manuscript (house number-traceability discipline).

Mirrors Gauge/Minos/Lethe consistency.py: regenerates ``numbers.tex`` from the reproduced,
committed-anchor-traced results so that NO number in ``augur.tex`` is hand-typed -- every value
originates in a reproduction artifact (results/*.json) that itself traces to a committed source
(anchors/anchors.json -> Gauge results / CITATIONS.md). Then it verifies that every ``\num*``
macro the manuscript uses is defined, and asserts the load-bearing spine invariants hold.

Inputs (must exist -- run ``bash reproduce.sh`` first, which regenerates them):
  anchors/anchors.json
  results/crlb_wall.json, results/retest_ci.json, results/dstar_ktrans.json

Output:
  paper/numbers.tex  (AUTO-GENERATED -- do not edit by hand)

Exit code: 0 = numbers.tex regenerated, all macros defined, invariants hold; non-zero otherwise.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
AUGUR = HERE.parent
RESDIR = AUGUR / "results"
ANCHORS = AUGUR / "anchors" / "anchors.json"
TEX = HERE / "augur.tex"
NUMBERS = HERE / "numbers.tex"


def _load(p: Path) -> dict:
    if not p.exists():
        print(f"CONSISTENCY FAIL: missing {p.relative_to(AUGUR)} -- run `bash reproduce.sh` first",
              file=sys.stderr)
        raise SystemExit(2)
    return json.loads(p.read_text())


def build_numbers() -> dict:
    """Returns {macro_name: (latex_value, provenance_comment)} -- the single source of truth."""
    rt = _load(RESDIR / "retest_ci.json")
    cr = _load(RESDIR / "crlb_wall.json")
    dk = _load(RESDIR / "dstar_ktrans.json")

    ds = rt["Dstar"]
    d = rt["D"]
    boot = ds["ci95_bootstrap_BCa_carried"]
    dboot = d["ci95_bootstrap_BCa"]
    sun = next(r for r in dk["rows"] if r["study"].startswith("Sun"))
    yang = next(r for r in dk["rows"] if r["study"].startswith("Yang"))

    n = {
        # --- D* test-retest anchor (Gauge Checkpoint D; ACRIN-6698, CC-BY-4.0) -------------
        "numDstarR": (f"{ds['spearman_r']:+.2f}", "D* width-vs-repeatability Spearman r"),
        "numDstarP": (f"{ds['p']:.2f}", "D* Spearman two-sided p"),
        "numDstarN": (f"{rt['n_pairs']}", "same-day test-retest pairs"),
        "numDstarCIlo": (f"{boot[0]:+.2f}", "D* BCa bootstrap 95% CI lower"),
        "numDstarCIhi": (f"{boot[1]:+.2f}", "D* BCa bootstrap 95% CI upper"),
        "numDR": (f"{d['spearman_r']:+.2f}", "D width-vs-repeatability Spearman r"),
        "numDCIlo": (f"{dboot[0]:+.2f}", "D BCa bootstrap 95% CI lower"),
        "numDCIhi": (f"{dboot[1]:+.2f}", "D BCa bootstrap 95% CI upper"),
        # --- CRLB identifiability wall (Gauge conditional_attack; reproduced this build) ----
        "numCRLBgrowth": (f"{cr['anchor']['crlb_growth_factor']:.0f}", "absolute CRLB(D*) growth factor"),
        "numCRLBgrowthRepro": (f"{cr['reproduced']['crlb_growth_factor']:.1f}",
                               "reproduced CRLB(D*) growth factor (this build)"),
        "numCRLBtercileRatio": (f"{cr['anchor']['crlb_over_tercile_width_hi']:.2f}",
                                "high-D* CRLB(D*)/tercile-width (cohort-realized)"),
        "numWidthCRLBr": (f"{cr['anchor']['conformal_width_crlb_r']:.2f}",
                          "conformal width vs CRLB Spearman r"),
        # --- external cross-modal D*-Ktrans (Sun 2019 / Yang 2019; literature) -------------
        "numSunR": (f"{sun['Dstar_Ktrans_r']:.3f}", "Sun 2019 D*-Ktrans r"),
        "numSunComposite": (f"{sun['composite_fDstar_Ktrans_r']:.3f}", "Sun 2019 f*D*-Ktrans r"),
        "numYangICC": (f"{yang['Dstar_reproducibility_ICC']:.2f}", "Yang 2019 D* reproducibility ICC"),
    }
    return n


def write_numbers(nums: dict) -> None:
    lines = [
        "% AUTO-GENERATED by paper/consistency.py from reproduced, anchor-traced results.",
        "% DO NOT EDIT BY HAND. Regenerate with: bash reproduce.sh  (or bash paper/build.sh).",
        "% Every value traces: results/*.json -> anchors/anchors.json -> committed Gauge / CITATIONS.",
        "",
    ]
    for k, (v, why) in nums.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}  % {why}")
    NUMBERS.write_text("\n".join(lines) + "\n")


def verify_macros(nums: dict) -> list[str]:
    """Every \\num* used in augur.tex must be defined; warn on defined-but-unused."""
    problems = []
    if not TEX.exists():
        return [f"manuscript {TEX.relative_to(AUGUR)} not found"]
    tex = TEX.read_text()
    import re
    used = set(re.findall(r"\\(num[A-Za-z]+)\b", tex))
    defined = set(nums)
    undefined = sorted(used - defined)
    unused = sorted(defined - used)
    if undefined:
        problems.append(f"macros used in augur.tex but NOT defined: {undefined}")
    if unused:
        print(f"  note: macros defined but unused in augur.tex: {unused}")
    return problems


def check_invariants() -> list[str]:
    """Load-bearing spine invariants -- the honest negative must survive regeneration."""
    rt = _load(RESDIR / "retest_ci.json")
    cr = _load(RESDIR / "crlb_wall.json")
    fails = []
    if not rt["Dstar"]["spans_zero"]:
        fails.append("D* test-retest 95% CI must span zero (the null is load-bearing)")
    if not rt["crosscheck"]["Dstar_fisher_pass"]:
        fails.append("reproduced D* Fisher-z CI must match the committed anchor")
    if rt["D"]["spearman_r"] <= 0:
        fails.append("companion D correlation must be positive (the contrast)")
    if not cr["crosscheck"]["growth_factor_pass"]:
        fails.append("reproduced CRLB growth must match the anchor (~6x)")
    if not cr["crosscheck"]["wall_present_pass"]:
        fails.append("CRLB(D*) must reach the tercile-width scale (the wall)")
    return fails


def main() -> int:
    print("Augur CP4 consistency gate")
    print("=" * 64)
    nums = build_numbers()
    write_numbers(nums)
    print(f"  regenerated numbers.tex ({len(nums)} macros) from reproduced anchor-traced results")

    problems = verify_macros(nums)
    fails = check_invariants()

    if problems:
        for p in problems:
            print(f"  MACRO FAIL: {p}", file=sys.stderr)
    if fails:
        for f in fails:
            print(f"  INVARIANT FAIL: {f}", file=sys.stderr)
    if problems or fails:
        print("=" * 64)
        print("CONSISTENCY GATE: FAIL", file=sys.stderr)
        return 1
    print("  all manuscript macros defined; load-bearing spine invariants hold")
    print("=" * 64)
    print("CONSISTENCY GATE: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
