"""Synthetic cohort substrate via read-only Lattice.

Gnomon's synthetic **ground truth** is drawn from the **Lattice** DRO, imported
read-only through :mod:`gnomon._paths` (``lattice`` only; Caliper forbidden). The
signals and noise are then generated by Gnomon's own clean-room forward model
(:mod:`gnomon.forward`), which is what CP2 reimplements -- so the *data substrate* is
Lattice while the *signal model* is independent.

The headline design reproduces Fashion's 9-cell set (README.md:58-59): 3 ground-truth
conditions x SNR {10, 20, 40} x 200 noise realizations, at the clinical-sparse 8-b
scheme. The 3 truths are selected from a Lattice prior draw by D* quantile (low /
median / high) so the set spans the pseudo-diffusion identifiability axis that drives
the coverage story. Everything is reproducible from ``manifest.MASTER_SEED``.
"""
from __future__ import annotations

from dataclasses import dataclass
import numpy as np

from . import _paths, forward as F
from .manifest import B_SCHEMES, SNR_HEADLINE, N_TRUTHS, N_NOISE, MASTER_SEED


def load_lattice():
    """Resolve and return the read-only ``lattice`` module (Caliper stays out)."""
    _paths.ensure_lattice(strict=True)
    import lattice  # resolved read-only via _paths
    import lattice.cohort  # noqa: F401  (ensure submodule import)
    return lattice


@dataclass
class HeadlineCohort:
    bvalues: np.ndarray       # (nb,)
    params_true: np.ndarray   # (n, 3) physical (D, Dstar, f)
    signals: np.ndarray       # (n, nb) noisy
    signals_clean: np.ndarray # (n, nb)
    snr: np.ndarray           # (n,)
    sigma: np.ndarray         # (n,) noise SD
    truth_id: np.ndarray      # (n,) which of the N_TRUTHS
    substrate: str = "lattice"

    @property
    def n(self):
        return self.params_true.shape[0]


def select_truths(n_truths=N_TRUTHS, pool=60, seed=MASTER_SEED, prior="realistic"):
    """Pick ``n_truths`` ground-truth (D, Dstar, f) rows from a Lattice prior draw.

    Selected by D* quantile (low/median/high) so the headline set spans the
    pseudo-diffusion identifiability axis. Substrate = Lattice (read-only).
    """
    lat = load_lattice()
    rng = np.random.default_rng(seed)
    P = np.asarray(lat.cohort.sample_params(pool, rng, prior=prior), dtype=float)
    order = np.argsort(P[:, 1])  # by Dstar
    qs = np.linspace(0.2, 0.8, n_truths)
    idx = [order[int(round(q * (pool - 1)))] for q in qs]
    return P[idx]


def make_headline_cohort(seed=MASTER_SEED, n_noise=N_NOISE, snrs=SNR_HEADLINE,
                         scheme="clinical_sparse"):
    """Build the 3-truth x SNR x noise headline cohort (Lattice truths + clean-room noise)."""
    b = np.array(B_SCHEMES[scheme], dtype=float)
    truths = select_truths(seed=seed)
    rng = np.random.default_rng(seed + 7)
    rows_p, rows_sig, rows_clean, rows_snr, rows_sigma, rows_tid = [], [], [], [], [], []
    for ti, (D, Dstar, f) in enumerate(truths):
        clean = F.ivim(b, D, Dstar, f, s0=1.0)  # (nb,)
        for snr in snrs:
            sigma = F.snr_to_sigma(snr, s0=1.0)
            block = F.add_rician_noise(np.tile(clean, (n_noise, 1)), sigma, rng)
            rows_sig.append(block)
            rows_clean.append(np.tile(clean, (n_noise, 1)))
            rows_p.append(np.tile([D, Dstar, f], (n_noise, 1)))
            rows_snr.append(np.full(n_noise, snr, dtype=float))
            rows_sigma.append(np.full(n_noise, sigma, dtype=float))
            rows_tid.append(np.full(n_noise, ti, dtype=int))
    return HeadlineCohort(
        bvalues=b,
        params_true=np.vstack(rows_p),
        signals=np.vstack(rows_sig),
        signals_clean=np.vstack(rows_clean),
        snr=np.concatenate(rows_snr),
        sigma=np.concatenate(rows_sigma),
        truth_id=np.concatenate(rows_tid))
