#!/usr/bin/env python3
"""
Forge Monte Carlo Geometry and Parameter Deck Generator.
Generates randomized voxelized phantoms, beam/source configurations, 
magnetic fields, and TOPAS text decks.
"""

import os
import json
import numpy as np

def generate_layered_phantom(Nx=60, Ny=60, Nz=60, seed=42):
    """
    Generates a 3D voxelized phantom with randomized layers and an air gap.
    Material Tags:
      0: G4_AIR (Density ~0.0012 g/cm3)
      1: G4_LUNG_ICRP (Density ~0.26 g/cm3)
      2: G4_WATER (Density ~1.0 g/cm3)
      3: G4_BONE_COMPACT_ICRU (Density ~1.85 g/cm3)
    """
    rng = np.random.default_rng(seed)
    
    # Initialize as water/soft tissue (tag 2)
    phantom = np.full((Nx, Ny, Nz), 2, dtype=np.int16)
    
    # Determine random slab interfaces along the Z (depth) axis
    # The beam travels along +Z direction.
    # We want a soft-tissue slab -> air gap -> lung/bone/soft-tissue slab.
    
    # Let's divide Z axis (Nz voxels) into 4-5 slabs
    # Slab 1: Tissue (always first to build buildup region)
    # Slab 2: Air gap (crucial for ERE)
    # Slab 3: Lung or Bone or Tissue
    # Slab 4: Bone or Lung or Tissue
    
    z_slab1 = rng.integers(15, 22) # Soft tissue region
    z_gap_thickness = rng.integers(6, 12) # Air gap thickness
    z_slab2 = z_slab1 + z_gap_thickness
    
    z_slab3 = rng.integers(z_slab2 + 10, Nz - 10)
    
    # Apply tags
    # Slab 1: Soft tissue (already 2)
    
    # Slab 2: Air gap
    phantom[:, :, z_slab1:z_slab2] = 0
    
    # Slab 3: Lung (1) or Bone (3) or Soft tissue (2)
    slab3_material = rng.choice([1, 2, 3])
    phantom[:, :, z_slab2:z_slab3] = slab3_material
    
    # Slab 4: Bone (3) or Lung (1)
    slab4_material = rng.choice([1, 3])
    phantom[:, :, z_slab3:] = slab4_material
    
    return phantom, {
        "slab_boundaries_z": [int(z_slab1), int(z_slab2), int(z_slab3)],
        "materials": ["G4_WATER", "G4_AIR", 
                      "G4_LUNG_ICRP" if slab3_material == 1 else ("G4_WATER" if slab3_material == 2 else "G4_BONE_COMPACT_ICRU"),
                      "G4_LUNG_ICRP" if slab4_material == 1 else "G4_BONE_COMPACT_ICRU"]
    }

def generate_case_deck(case_id, seed, output_dir="cases"):
    """
    Generates a single randomized MC case, writes the binary voxel grid 
    and the TOPAS parameter text deck.
    """
    os.makedirs(output_dir, exist_ok=True)
    rng = np.random.default_rng(seed)
    
    # Grid configuration
    Nx, Ny, Nz = 60, 60, 60
    dx, dy, dz = 2.5, 2.5, 2.5 # mm
    
    # Voxel phantom generation
    phantom, meta = generate_layered_phantom(Nx, Ny, Nz, seed)
    
    # Save raw voxel grid as short (int16) binary file
    bin_filename = f"case_{case_id}.bin"
    bin_filepath = os.path.join(output_dir, bin_filename)
    phantom.tofile(bin_filepath)
    
    # B-field: transverse field (either in X or Y direction, or slightly angled)
    # Default 1.5 T transverse (MRI-Linac)
    b_strength = 1.5 # Tesla
    b_dir = rng.choice(["X", "Y"])
    bx_dir = 1.0 if b_dir == "X" else 0.0
    by_dir = 1.0 if b_dir == "Y" else 0.0
    bz_dir = 0.0
    
    # Source / Beam configuration
    # 150 MeV protons or 6 MV photons
    particle = rng.choice(["proton", "gamma"])
    if particle == "proton":
        energy = rng.uniform(120.0, 180.0) # MeV
    else:
        energy = rng.uniform(4.0, 10.0) # MeV
        
    # Statistical uncertainty target: controls histories
    # Let's set a baseline of 5000 histories for benchmarking, 
    # which is standard for a quick run.
    histories = 50000
    
    # Topas Deck Generation
    deck_filename = f"case_{case_id}.txt"
    deck_filepath = os.path.join(output_dir, deck_filename)
    
    deck_content = f"""# TOPAS Parameter Deck for Case {case_id}
# Generated by Forge (geom.py) - Seed: {seed}

# ====================================================================
# WORLD GEOMETRY
# ====================================================================
d:Ge/World/HLX = 20.0 cm
d:Ge/World/HLY = 20.0 cm
d:Ge/World/HLZ = 30.0 cm
s:Ge/World/Material = "G4_AIR"

# ====================================================================
# PATIENT/PHANTOM (VOXELIZED)
# ====================================================================
s:Ge/Patient/Type = "TsImageCube"
s:Ge/Patient/Parent = "World"
s:Ge/Patient/InputDirectory = "./"
s:Ge/Patient/InputFile = "{bin_filename}"
s:Ge/Patient/DataType = "short"
i:Ge/Patient/NumberOfVoxelsX = {Nx}
i:Ge/Patient/NumberOfVoxelsY = {Ny}
i:Ge/Patient/NumberOfVoxelsZ = {Nz}
d:Ge/Patient/VoxelSizeX = {dx} mm
d:Ge/Patient/VoxelSizeY = {dy} mm
d:Ge/Patient/VoxelSizeZ = {dz} mm
d:Ge/Patient/TransX = 0.0 cm
d:Ge/Patient/TransY = 0.0 cm
d:Ge/Patient/TransZ = 0.0 cm
d:Ge/Patient/RotX = 0.0 deg
d:Ge/Patient/RotY = 0.0 deg
d:Ge/Patient/RotZ = 0.0 deg

s:Ge/Patient/ImagingToMaterialConverter = "MaterialTagNumber"
iv:Ge/Patient/MaterialTagNumbers = 4 0 1 2 3
sv:Ge/Patient/MaterialNames = 4 "G4_AIR" "G4_LUNG_ICRP" "G4_WATER" "G4_BONE_COMPACT_ICRU"

# ====================================================================
# MAGNETIC FIELD (TRANSVERSE Dipole)
# ====================================================================
s:Ge/Patient/Field = "DipoleMagnet"
u:Ge/Patient/MagneticFieldDirectionX = {bx_dir}
u:Ge/Patient/MagneticFieldDirectionY = {by_dir}
u:Ge/Patient/MagneticFieldDirectionZ = {bz_dir}
d:Ge/Patient/MagneticFieldStrength = {b_strength} tesla

# ====================================================================
# BEAM SOURCE (Proton or Photon)
# ====================================================================
s:So/Beam/Type = "Beam"
s:So/Beam/Component = "World"
s:So/Beam/BeamParticle = "{particle}"
d:So/Beam/BeamEnergy = {energy:.4f} MeV
u:So/Beam/BeamEnergySpread = 0.0
s:So/Beam/BeamPositionDistribution = "Gaussian"
s:So/Beam/BeamPositionCutoffShape = "Rectangle"
d:So/Beam/BeamPositionCutoffX = 10.0 cm
d:So/Beam/BeamPositionCutoffY = 10.0 cm
d:So/Beam/BeamPositionSpreadX = 5.0 mm
d:So/Beam/BeamPositionSpreadY = 5.0 mm
s:So/Beam/BeamAngularDistribution = "None"
d:So/Beam/TransX = 0.0 cm
d:So/Beam/TransY = 0.0 cm
d:So/Beam/TransZ = -25.0 cm
d:So/Beam/RotX = 0.0 deg
d:So/Beam/RotY = 0.0 deg
d:So/Beam/RotZ = 0.0 deg
i:So/Beam/NumberOfHistoriesInRun = {histories}

# ====================================================================
# SCORING (3D Dose to Medium)
# ====================================================================
s:Sc/Dose/Quantity = "DoseToMedium"
s:Sc/Dose/Component = "Patient"
s:Sc/Dose/OutputFile = "dose_case_{case_id}"
s:Sc/Dose/OutputType = "csv"
s:Sc/Dose/IfOutputFileAlreadyExists = "Overwrite"

# ====================================================================
# TIMING & CONTROLS
# ====================================================================
# s:Gr/View/Type = "OpenGL"
# b:Gr/View/Active = "False"
i:Ts/ShowHistoryCountAtInterval = 1000
i:Ts/Seed = {seed}
"""
    with open(deck_filepath, "w") as f:
        f.write(deck_content)
        
    return {
        "case_id": case_id,
        "seed": int(seed),
        "bin_file": bin_filename,
        "deck_file": deck_filename,
        "phantom_meta": meta,
        "magnetic_field": {
            "strength_tesla": b_strength,
            "direction": [bx_dir, by_dir, bz_dir]
        },
        "source": {
            "particle": particle,
            "energy_mev": float(energy),
            "histories": histories
        },
        "dimensions": [Nx, Ny, Nz],
        "voxel_sizes_mm": [dx, dy, dz]
    }

def main():
    K = 12
    base_seed = 1000
    cases_meta = []
    
    print(f"Generating {K} randomized cases in 'cases/'...")
    for k in range(1, K + 1):
        seed = base_seed + k
        case_info = generate_case_deck(k, seed, "cases")
        cases_meta.append(case_info)
        print(f"  - Case {k} generated (Seed={seed}, Particle={case_info['source']['particle']}, B_dir={case_info['magnetic_field']['direction']})")
        
    # Write manifest file
    manifest_filepath = os.path.join("cases", "manifest.json")
    with open(manifest_filepath, "w") as f:
        json.dump({
            "num_cases": K,
            "base_seed": base_seed,
            "cases": cases_meta
        }, f, indent=2)
    print(f"Generated manifest: {manifest_filepath}")

if __name__ == "__main__":
    main()
