#!/usr/bin/env python
"""CP3 validation: Echo's repeatability scale-calibration on real ACRIN-6698 test--retest.

PROVISIONAL: consumes Caliper's conformal ruler and is contextualised by Fashion's
posterior / Gauge's baseline (in review). Every number is regenerated by this seeded script.

PINNED METHOD (frozen at the CP2->CP3 halt, no tuning):
  * Deployer: split-conformal residual offsets (Caliper) on a synthetic 4-b IVIM cohort,
    calibrated at an EFFECTIVE ROI-mean SNR = single-voxel SNR x sqrt(n_vox_i) per tumor
    (n_vox from the committed provenance manifest), interpolated from a common-random-number
    offset table so offsets are a smooth monotone function of SNR.
  * Headline: single-voxel SNR = 20. Sensitivity sweep: Gauge's grid {10,20,30,50,100}.
  * Statistic: test-retest coverage c, scale ratio R = sigma_implied/sigma_repeat,
    z-dispersion; BCa 95% CIs; symmetrized A<->B.

Locked PASS/FAIL (CP0): PASS(D) iff coverage CI excludes 0.65 AND 1.00 AND point in
[0.72,0.96]; else -> Lethe (under-scaled / saturated / redundant-with-Gauge). D* is an
identifiability probe, not pass/fail.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from echo_repeat import invivo, statistic as st  # noqa: E402

DATA_DIR = ROOT / "data" / "invivo_retest"
MANIFEST = ROOT / "results" / "invivo_provenance.json"
PARAMS = ("D", "Dstar", "f")
PASS_LO, PASS_HI = 0.72, 0.96
LETHE_UNDER, LETHE_SAT = 0.65, 0.99
SNR_GRID = (10.0, 20.0, 30.0, 50.0, 100.0)   # Gauge DEFAULT_SNR_GRID (single-voxel)
HEADLINE_SNR = 20.0


def load_pairs(data_dir, manifest):
    """Return (ids, est_a, est_b, nvox): segmented IVIM fits for both repeats + ROI sizes."""
    nvox_by_id = {}
    if Path(manifest).exists():
        m = json.loads(Path(manifest).read_text())
        for e in m.get("exams", []):
            nvox_by_id[e["tumor"]] = 0.5 * (e["n_tumor_voxels_a"] + e["n_tumor_voxels_b"])
    ids, ea, eb, nv = [], [], [], []
    for fp in sorted(Path(data_dir).glob("*.json")):
        rec = json.loads(fp.read_text())
        tid = rec["tumor"]
        b = np.asarray(rec.get("bvals", invivo.ACRIN_BVALS), float)
        ea.append(invivo.segmented_fit(np.asarray(rec["signal_a"], float), b))
        eb.append(invivo.segmented_fit(np.asarray(rec["signal_b"], float), b))
        ids.append(tid)
        nv.append(nvox_by_id.get(tid, np.nan))
    return ids, np.asarray(ea, float), np.asarray(eb, float), np.asarray(nv, float)


def offset_table(level, n_cal, seed, lo=50.0, hi=12000.0, n_pts=26):
    """Common-random-number offset(SNR) table for [D,Dstar,f]; monotone in SNR."""
    snrs = np.geomspace(lo, hi, n_pts)
    offs = np.empty((n_pts, 3))
    for i, s in enumerate(snrs):
        dep = invivo.build_deployer(level=level, n_cal=n_cal, snr=float(s), seed=seed)
        offs[i] = dep.offsets
        backend = dep.__dict__.get("backend")
    return snrs, offs, backend


def per_tumor_offsets(base_snr, nvox, snrs, offs):
    """Interpolate each tumor's [D,Dstar,f] offset at eff SNR = base_snr*sqrt(nvox)."""
    eff = base_snr * np.sqrt(nvox)
    eff = np.clip(eff, snrs[0], snrs[-1])
    return np.stack([np.interp(eff, snrs, offs[:, k]) for k in range(3)], axis=1)  # (n,3)


def coverage_for(base_snr, est_a, est_b, nvox, snrs, offs, level, *, n_boot=0, seed=0):
    """Coverage + (optional BCa CI) + scale ratio for parameter D at a given base SNR."""
    pt = per_tumor_offsets(base_snr, nvox, snrs, offs)  # (n,3)
    out = {}
    z = st.norm_ppf(1.0 - level / 2.0)
    for k, name in enumerate(PARAMS):
        a, b = est_a[:, k], est_b[:, k]
        off = pt[:, k]
        ok = np.isfinite(a) & np.isfinite(b) & np.isfinite(off)
        a, b, off = a[ok], b[ok], off[ok]
        lo_a, hi_a = a - off, a + off
        lo_b, hi_b = b - off, b + off
        if n_boot > 0:
            res = st.evaluate(name, a, b, lo_a, hi_a, lo_b, hi_b, level=level,
                              n_boot=n_boot, seed=seed + k)
            d = res.as_dict()
        else:
            d = {"param": name, "n": int(a.size),
                 "coverage": st.test_retest_coverage(a, b, lo_a, hi_a, lo_b, hi_b),
                 "coverage_ci": [float("nan"), float("nan")],
                 "z_dispersion": st.standardized_residual_dispersion(a, b, 2 * off, 2 * off, level),
                 "spearman_width_vs_repeat": st.spearman(off, np.abs(b - a))}
        # scale ratio R = sigma_implied / sigma_repeat (robust)
        sigma_implied = float(np.median(off)) / z
        delta = b - a
        sigma_repeat = 1.4826 * float(np.median(np.abs(delta - np.median(delta)))) / math.sqrt(2.0)
        d["sigma_implied"] = sigma_implied
        d["sigma_repeat"] = sigma_repeat
        d["scale_ratio_R"] = sigma_implied / sigma_repeat if sigma_repeat > 0 else float("nan")
        out[name] = d
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--level", type=float, default=0.10)
    ap.add_argument("--n-cal", type=int, default=3000)
    ap.add_argument("--n-boot", type=int, default=4000)
    ap.add_argument("--seed", type=int, default=20260613)  # Gauge DEFAULT_SEED
    ap.add_argument("--data-dir", default=str(DATA_DIR))
    args = ap.parse_args()

    ids, est_a, est_b, nvox = load_pairs(args.data_dir, MANIFEST)
    if len(ids) == 0:
        print("DATA GATE NOT SATISFIED: no signals. Run scripts/fetch_invivo.py --fetch "
              "(CP2), or fall back to scripts/run_harness.py (Reverb).", file=sys.stderr)
        return 3
    if not np.all(np.isfinite(nvox)):
        nvox = np.where(np.isfinite(nvox), nvox, np.nanmedian(nvox))

    snrs, offs, backend = offset_table(args.level, args.n_cal, args.seed)

    # headline (BCa) + sensitivity curve (point estimates)
    headline = coverage_for(HEADLINE_SNR, est_a, est_b, nvox, snrs, offs, args.level,
                            n_boot=args.n_boot, seed=args.seed)
    sweep = {}
    for s in SNR_GRID:
        sweep[s] = {p: coverage_for(s, est_a, est_b, nvox, snrs, offs, args.level)[p]["coverage"]
                    for p in PARAMS}

    # crossing: single-voxel SNR where c_D == analytic repeat target (0.755)
    target = st.analytic_repeat_coverage(args.level)
    cs = np.array([sweep[s]["D"] for s in SNR_GRID])
    grid = np.array(SNR_GRID)
    order = np.argsort(grid)  # coverage decreases with SNR; for interp need increasing x->use coverage
    cross = None
    cv = cs[np.argsort(-grid)]; gv = grid[np.argsort(-grid)]  # ascending coverage
    if cv.min() <= target <= cv.max():
        cross = float(np.interp(target, cv, gv))

    # --- locked gate on D (headline) ---
    d = headline["D"]
    c = d["coverage"]; clo, chi = d["coverage_ci"]
    saturated = (c >= LETHE_SAT) or (np.isfinite(chi) and chi >= 1.0 - 1e-9)
    under = c < LETHE_UNDER
    discriminative = np.isfinite(chi) and chi < 1.0 - 1e-9
    passed = (np.isfinite(clo) and clo > LETHE_UNDER) and discriminative and (PASS_LO <= c <= PASS_HI)
    verdict = "PASS" if passed else "LETHE"

    outdir = ROOT / "results"; outdir.mkdir(exist_ok=True)
    payload = {"provisional": True, "kind": "real-data-validation",
               "seed": args.seed, "level": args.level, "n": d["n"],
               "conformal_backend": backend, "headline_single_voxel_snr": HEADLINE_SNR,
               "analytic_repeat_target": target,
               "headline": headline, "sensitivity_single_voxel_snr": {str(k): v for k, v in sweep.items()},
               "crossing_single_voxel_snr_for_target": cross,
               "gauge_baseline": {"D_spearman": 0.60, "D_ci": [0.42, 0.72], "Dstar_spearman": -0.17,
                                  "note": "Gauge paper Sec 4.2.2 -- RANK (Spearman) check"},
               "gate": {"coverage_D": c, "coverage_D_ci": [clo, chi],
                        "thresholds": {"pass_lo": PASS_LO, "pass_hi": PASS_HI,
                                       "lethe_under": LETHE_UNDER, "lethe_sat": LETHE_SAT},
                        "under": bool(under), "saturated": bool(saturated),
                        "discriminative": bool(discriminative), "VERDICT": verdict}}
    (outdir / "RESULTS_VALIDATION.json").write_text(json.dumps(payload, indent=2))

    L = ["# CP3 validation -- repeatability scale-calibration on ACRIN-6698 (PROVISIONAL)", "",
         f"n={d['n']} test-retest tumors, level={args.level} (90% intervals), seed={args.seed}, "
         f"conformal backend: {backend}.",
         f"Analytic repeat-coverage target for a correctly measurement-scaled interval: "
         f"**{target:.3f}** (NOT 0.90).", "",
         f"## Headline (single-voxel SNR = {HEADLINE_SNR:g}, eff SNR = SNR x sqrt(n_vox))", "",
         "| param | coverage [BCa 95%] | scale ratio R=σ_impl/σ_rep | z-disp | σ_implied | σ_repeat |",
         "|---|---|---|---|---|---|"]
    for p in PARAMS:
        r = headline[p]
        ci = r["coverage_ci"]
        L.append(f"| {p} | {r['coverage']:.3f} [{ci[0]:.3f},{ci[1]:.3f}] | {r['scale_ratio_R']:.3f} | "
                 f"{r['z_dispersion']:.2f} | {r['sigma_implied']:.2e} | {r['sigma_repeat']:.2e} |")
    L += ["", "## Sensitivity: coverage(D) vs single-voxel SNR (honesty curve)", "",
          "| single-voxel SNR | " + " | ".join(f"{s:g}" for s in SNR_GRID) + " |",
          "|" + "---|" * (len(SNR_GRID) + 1),
          "| coverage(D) | " + " | ".join(f"{sweep[s]['D']:.3f}" for s in SNR_GRID) + " |",
          "", f"Crossing (single-voxel SNR where coverage(D)=={target:.3f}): "
          f"{('%.1f' % cross) if cross is not None else 'outside grid'}.",
          "", f"Gauge Sec 4.2.2 baseline (RANK): D Spearman r=+0.60 [0.42,0.72]; D* null. "
          f"Echo measures SCALE (coverage), an independent axis.", "",
          f"## GATE (parameter D): **{verdict}**",
          f"- coverage_D = {c:.3f}, CI [{clo:.3f},{chi:.3f}]; under={under}, saturated={saturated}, "
          f"discriminative={discriminative}",
          f"- R(D) = {d['scale_ratio_R']:.3f}  (R<1: interval narrower than repeatability; "
          f"R>1: wider)"]
    (outdir / "RESULTS_VALIDATION.md").write_text("\n".join(L))
    print("\n".join(L))
    print(f"\nVERDICT={verdict}; wrote RESULTS_VALIDATION.{{json,md}}")
    # Exit 0 = verdict cleanly RENDERED (PASS or LETHE -- both valid); the verdict itself is
    # in the output/JSON, not the exit status. (3 = data gate unsatisfied; 1 = error.)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
