#!/usr/bin/env python
"""CP3 validation: Echo's repeatability scale-calibration on real ACRIN-6698 test--retest.

PROVISIONAL: consumes Caliper's conformal ruler and is contextualised by Fashion's
posterior / Gauge's baseline (in review). Every number here is regenerated by this seeded
script; see ASSUMPTIONS.md.

Locked PASS/FAIL (set at CP0, no tuning):
  * PASS (parameter D): coverage BCa-95%-CI excludes 0.65 AND excludes 1.00; point in
    [0.72, 0.96].
  * -> Lethe if: c_D < 0.65 (under-scaled); c_D >= 0.99 / CI includes 1.0 (saturated, no
    scale content); or the coverage signal is statistically redundant with Gauge's Spearman.
  * D* is a pre-registered identifiability consistency probe (not pass/fail).

This is the honest gate. It does not tune; it reports and routes.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from echo_repeat import invivo, statistic as st  # noqa: E402

DATA_DIR = ROOT / "data" / "invivo_retest"
PARAMS = ("D", "Dstar", "f")

# Locked thresholds (CP0)
PASS_LO, PASS_HI = 0.72, 0.96
LETHE_UNDER, LETHE_SAT = 0.65, 0.99


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--level", type=float, default=0.10)
    ap.add_argument("--n-cal", type=int, default=2000)
    ap.add_argument("--n-boot", type=int, default=4000)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--data-dir", default=str(DATA_DIR))
    args = ap.parse_args()

    # --- CP2 data gate enforcement: real signals must be present (no silent skip) ---
    try:
        est_a, est_b = invivo.load_test_retest(args.data_dir)
    except FileNotFoundError as e:
        print(f"DATA GATE NOT SATISFIED: {e}", file=sys.stderr)
        print("Run scripts/fetch_invivo.py --from-gauge first, or fall back to "
              "scripts/run_harness.py (Reverb).", file=sys.stderr)
        return 3

    dep = invivo.build_deployer(level=args.level, n_cal=args.n_cal, seed=args.seed)
    results = {}
    for k, name in enumerate(PARAMS):
        ea, eb = est_a[:, k], est_b[:, k]
        ok = np.isfinite(ea) & np.isfinite(eb)
        ea, eb = ea[ok], eb[ok]
        lo_a, hi_a = ea - dep.offsets[k], ea + dep.offsets[k]
        lo_b, hi_b = eb - dep.offsets[k], eb + dep.offsets[k]
        res = st.evaluate(name, ea, eb, lo_a, hi_a, lo_b, hi_b,
                          level=args.level, n_boot=args.n_boot, seed=args.seed + k)
        results[name] = res.as_dict()

    # --- apply the locked gate on D ---
    d = results["D"]
    c, (clo, chi) = d["coverage"], d["coverage_ci"]
    saturated = (c >= LETHE_SAT) or (chi >= 1.0 - 1e-9)
    under = c < LETHE_UNDER
    discriminative = chi < 1.0 - 1e-9
    passed = (clo > LETHE_UNDER) and discriminative and (PASS_LO <= c <= PASS_HI)
    verdict = "PASS" if passed else ("LETHE" if (under or saturated) else "LETHE")

    outdir = ROOT / "results"
    outdir.mkdir(exist_ok=True)
    payload = {"provisional": True, "kind": "real-data-validation", "seed": args.seed,
               "level": args.level, "conformal_backend": dep.__dict__.get("backend"),
               "n": d["n"], "params": results,
               "gate": {"coverage_D": c, "coverage_D_ci": [clo, chi],
                        "thresholds": {"pass_lo": PASS_LO, "pass_hi": PASS_HI,
                                       "lethe_under": LETHE_UNDER, "lethe_sat": LETHE_SAT},
                        "under": under, "saturated": saturated,
                        "discriminative": discriminative, "VERDICT": verdict}}
    (outdir / "RESULTS_VALIDATION.json").write_text(json.dumps(payload, indent=2))

    lines = ["# CP3 validation -- repeatability scale-calibration (PROVISIONAL)", "",
             f"n={d['n']} test-retest tumors, level={args.level} (90% intervals), "
             f"conformal backend: {dep.__dict__.get('backend')}", "",
             "| param | coverage [BCa 95%] | z-dispersion | Spearman(width,|Δ|) | "
             "analytic meas-only target |", "|---|---|---|---|---|"]
    for name in PARAMS:
        r = results[name]
        lines.append(
            f"| {name} | {r['coverage']:.3f} [{r['coverage_ci'][0]:.3f},"
            f"{r['coverage_ci'][1]:.3f}] | {r['z_dispersion']:.3f} | "
            f"{r['spearman_width_vs_repeat']:.3f} | {r['analytic_target_meas_only']:.3f} |")
    lines += ["", f"**GATE (parameter D): {verdict}**",
              f"- coverage_D = {c:.3f}, CI [{clo:.3f},{chi:.3f}]; "
              f"under={under}, saturated={saturated}, discriminative={discriminative}"]
    (outdir / "RESULTS_VALIDATION.md").write_text("\n".join(lines))
    print("\n".join(lines))
    print(f"\nVERDICT={verdict}; wrote {outdir/'RESULTS_VALIDATION.json'} and .md")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
