#!/usr/bin/env python
"""Numbers-gate for the retooled (boundary-railing-first) Fashion manuscript.

This is an *integration* gate, not a computation: every macro in ``numbers.tex``
is re-derived from already-validated, seeded result JSONs produced by two
upstream, independently CI'd subrepos --- nothing is recomputed here and nothing
is typed by hand:

  * Sextant (PR #29)  -- boundary-railing primary + cross-cohort replication
      Sextant/results/railing_results.json      (rates + bootstrap CIs)
      Sextant/results/osipi_provenance.json      (OSIPI dataset IDs)
      Sextant/results/tcga_lihc_provenance.json  (TCGA-LIHC dataset IDs)
  * Gnomon CP4 hand-off (PR #31) -- the clean-room ruler, reframed
      Gnomon/handoff/conditional_coverage.json  (per-D*-tercile, both SD conv.)
      Gnomon/results/reproduction.json           (keep-set: K1 clean-room rail,
                                                  K2 quantile marginal, K3 flow)

The gate (a) regenerates ``numbers.tex`` and (b) asserts internal/cross-source
consistency. Any failure exits non-zero and ABORTS the paper build, so a number
in the manuscript can never drift from its traced source. Honors the claims
ledger: the DROPPED marginal 0.30/0.67 headline is *guarded against* (asserted
absent as a coverage macro); only the honest-CRLB conditional table is emitted.

Stdlib only (json). No numpy, no recomputation -- runs anywhere.
"""
from __future__ import annotations

import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))           # repo root (../../)
_SEXTANT = os.path.join(_ROOT, "Sextant")
_GNOMON = os.path.join(_ROOT, "Gnomon")

_RAIL = os.path.join(_SEXTANT, "results", "railing_results.json")
_OSIPI_PROV = os.path.join(_SEXTANT, "results", "osipi_provenance.json")
_LIHC_PROV = os.path.join(_SEXTANT, "results", "tcga_lihc_provenance.json")
_COND = os.path.join(_GNOMON, "handoff", "conditional_coverage.json")
_REPRO = os.path.join(_GNOMON, "results", "reproduction.json")
_NUMBERS = os.path.join(_HERE, "numbers.tex")

# Sextant cohort name -> TeX macro prefix (mirrors Sextant's own gate)
RAIL_PREFIX = {
    "abdomen_homogeneous": "Homo",
    "abdomen_full": "Full",
    "lihc_liver_4b_0_50_500_800": "LihcFour",
    "lihc_liver_3b_50_400_800": "LihcThree",
}

# conditional-coverage estimator -> macro stem; convention -> macro stem;
# tercile cell -> macro stem.  All-letters (LaTeX command names take no digits).
COND_EST = {"Laplace_SD": "Lap", "MCMC_SD": "Mc", "MCMC_quantile_recommended": "Mq"}
COND_CONV = {"honest": "Hon", "floored": "Flo"}
COND_CELL = {"low_Dstar": "Low", "mid_Dstar": "Mid", "high_Dstar": "High", "pooled": "Pool"}


def _pct(x):
    return f"{100 * x:.1f}"


def _cov(x):
    return f"{x:.2f}"


def main():
    rail = json.load(open(_RAIL))
    cond = json.load(open(_COND))
    repro = json.load(open(_REPRO))
    osipi = json.load(open(_OSIPI_PROV))["dataset"]
    lihc = json.load(open(_LIHC_PROV))["dataset"]

    lines = [
        "% AUTO-GENERATED by paper_retool/consistency.py -- do not edit by hand.",
        "% Every macro traces to a seeded, CI'd result JSON in Sextant/ or Gnomon/.",
        "",
    ]

    def cmd(name, val):
        lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    problems = []

    # ---- 1. Boundary-railing across cohorts (Sextant) ---------------------
    meta = rail["meta"]
    cmd("railSeed", meta["seed"])
    cmd("railNboot", f"{meta['n_boot']:,}".replace(",", "{,}"))
    cmd("thrPoint", _pct(meta["registered_thresholds"]["point_min"]))
    cmd("thrCIlo", _pct(meta["registered_thresholds"]["ci_lo_min"]))
    cmd("fashionReported", _pct(meta["fashion_reported_homogeneous"]))
    cmd("fashionN", f"{meta['fashion_reported_n_high_snr']:,}".replace(",", "{,}"))

    cohorts = {c["name"]: c for c in rail["cohorts"]}
    for name, c in cohorts.items():
        pre = RAIL_PREFIX.get(name)
        if pre is None:
            continue
        t, ci, w = c["tight"], c["bootstrap_ci"], c.get("wide")
        if not (0 <= t["frac_railed"] <= 1):
            problems.append(f"{name}: frac out of [0,1]")
        if not (ci["lo"] <= ci["point"] <= ci["hi"]):
            problems.append(f"{name}: bootstrap CI does not bracket point")
        cmd(pre + "Frac", _pct(t["frac_railed"]))
        cmd(pre + "CIlo", _pct(ci["lo"]))
        cmd(pre + "CIhi", _pct(ci["hi"]))
        cmd(pre + "Lower", _pct(t["frac_lower"]))
        cmd(pre + "Upper", _pct(t["frac_upper"]))
        if w:
            cmd(pre + "Wide", _pct(w["frac_railed"]))
        cmd(pre + "N", f"{c['n_high_snr']:,}".replace(",", "{,}"))
        cmd(pre + "Verdict", c["verdict"]["label"].replace("_", "-"))
        if c.get("n_subjects"):
            cmd(pre + "Subj", c["n_subjects"])

    # ---- 2. Gnomon clean-room corroboration of K1 (real OSIPI rail) -------
    t1 = repro["targets"]["T1_railing_real"]
    cmd("gnomonRailFrac", _pct(t1["rebuilt"]))
    cmd("gnomonRailCIlo", _pct(t1["ci"][0]))
    cmd("gnomonRailCIhi", _pct(t1["ci"][1]))
    cmd("gnomonRailSnr", _pct(repro["real"]["rail_tol_1e-3_snr25"]["rate"]))
    if not t1["pass"]:
        problems.append("Gnomon T1 clean-room railing target did not pass")

    # ---- 3. Conditional coverage table (Gnomon, both SD conventions) ------
    cc = cond["conditional_coverage"]
    for est_key, est in COND_EST.items():
        if est_key not in cc:
            continue
        for conv_key, conv in COND_CONV.items():
            if conv_key not in cc[est_key]:
                continue
            block = cc[est_key][conv_key]
            for cell_key, cell in COND_CELL.items():
                if cell_key not in block:
                    continue
                pt = block[cell_key]["coverage"]
                lo, hi = block[cell_key]["ci"]
                if not (lo <= pt <= hi):
                    problems.append(f"cond {est_key}/{conv_key}/{cell_key}: CI brackets fail")
                stem = f"cov{est}{conv}{cell}"
                cmd(stem, _cov(pt))
                cmd(stem + "Lo", _cov(lo))
                cmd(stem + "Hi", _cov(hi))

    # ---- 4. Keep-set K2 (marginal quantile) + K3 (flow vs railed NLLS) ----
    syn = repro["synthetic"]
    cmd("margMqDstar", _cov(syn["T3c_mcmc_quantile_Dstar"]["coverage"]))
    cmd("margMqDstarLo", _cov(syn["T3c_mcmc_quantile_Dstar"]["ci"][0]))
    cmd("margMqDstarHi", _cov(syn["T3c_mcmc_quantile_Dstar"]["ci"][1]))
    cmd("margMqD", _cov(syn["T3c_mcmc_quantile_D"]["coverage"]))
    cmd("margMqF", _cov(syn["T3c_mcmc_quantile_f"]["coverage"]))

    flow = syn["T4_flow_vs_railed_nlls"]
    cmd("flowCov", _cov(flow["flow"]["coverage"]))
    cmd("nllsCov", _cov(flow["nlls_railed"]["coverage"]))
    cmd("flowEce", f"{flow['flow']['ece']:.3f}")
    cmd("nllsEce", f"{flow['nlls_railed']['ece']:.3f}")
    cmd("flowSharp", f"{flow['flow']['sharpness']:.3f}")
    cmd("nllsSharp", f"{flow['nlls_railed']['sharpness']:.3f}")
    gcov, gece, gsh = (
        flow["gap_cov_flow_minus_nlls"],
        flow["gap_ece_nlls_minus_flow"],
        flow["gap_sharp_nlls_minus_flow"],
    )
    cmd("gapCov", _cov(gcov["point"]))
    cmd("gapCovLo", _cov(gcov["ci"][0]))
    cmd("gapCovHi", _cov(gcov["ci"][1]))
    # K3 directionality: every gap CI must exclude 0.
    for label, g in (("cov", gcov), ("ece", gece), ("sharp", gsh)):
        lo, hi = g["ci"]
        if lo <= 0 <= hi:
            problems.append(f"K3 flow gap '{label}' CI includes 0 (not directional)")

    # ---- 5. Provenance / dataset IDs (Sextant manifests) -----------------
    cmd("osipiDOI", osipi["data_record_doi"])
    cmd("osipiRecord", osipi["data_record_doi"].split(".")[-1])
    cmd("osipiLicense", osipi["data_license"])
    cmd("osipiNvol", osipi["n_diffusion_volumes"])
    cmd("osipiNb", len(osipi["b_values_unique_s_per_mm2"]))
    cmd("osipiHomoN", osipi["roi_voxel_counts"]["mask_abdomen_homogeneous.nii.gz"])
    cmd("tcgaDOI", lihc["doi"])
    cmd("tcgaLicense", lihc["license"])
    cmd("tcgaNseries", lihc["n_series"])

    # ---- 6. Cross-source / ledger consistency assertions -----------------
    homo = cohorts.get("abdomen_homogeneous")
    if homo and abs(homo["tight"]["frac_railed"] - meta["fashion_reported_homogeneous"]) > 0.005:
        problems.append("Sextant homogeneous railing != Fashion's reported 54.7%")
    if homo and homo["n_high_snr"] != meta["fashion_reported_n_high_snr"]:
        problems.append("Sextant homogeneous high-SNR count != Fashion's 1618")
    # K1 cross-source: Sextant 54.7% and Gnomon clean-room must agree (CIs overlap).
    if homo:
        s_lo, s_hi = homo["bootstrap_ci"]["lo"], homo["bootstrap_ci"]["hi"]
        g_lo, g_hi = t1["ci"]
        if not (s_lo <= g_hi and g_lo <= s_hi):
            problems.append("Sextant and Gnomon real-data railing CIs do not overlap")
    # Gnomon's own reconstruction self-check must be green.
    if not cond.get("reconstruction_ok", False):
        problems.append("Gnomon conditional-coverage reconstruction_ok is False")
    # REFRAME R1 anchor: honest Laplace high-D* tercile is the kept finding (~0.63).
    lap_hon_high = cc["Laplace_SD"]["honest"]["high_Dstar"]["coverage"]
    if abs(lap_hon_high - 0.63) > 0.02:
        problems.append(f"honest Laplace high-D* = {lap_hon_high}, expected ~0.63 (R1)")
    # DROP D1 guard: the dropped 0.30/0.67 marginal severity must NOT appear as
    # an honest coverage we assert; the honest pooled values are undramatic.
    lap_hon_pool = cc["Laplace_SD"]["honest"]["pooled"]["coverage"]
    mc_hon_pool = cc["MCMC_SD"]["honest"]["pooled"]["coverage"]
    if lap_hon_pool < 0.5 or mc_hon_pool < 0.5:
        problems.append("honest pooled coverage looks like the DROPPED 0.30/0.67 headline")
    # The floored convention is the documented reconstruction of the old headline.
    lap_flo_pool = cc["Laplace_SD"]["floored"]["pooled"]["coverage"]
    if abs(lap_flo_pool - 0.68) > 0.02:
        problems.append(f"floored Laplace pooled = {lap_flo_pool}, expected ~0.68 (R3 reconstruction)")

    # ---- write + verdict -------------------------------------------------
    with open(_NUMBERS, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    if problems:
        print("NUMBERS-GATE FAILURES:")
        for p in problems:
            print("  -", p)
        sys.exit(1)
    n_macros = sum(1 for l in lines if l.startswith("\\newcommand"))
    print(f"numbers-gate OK: {n_macros} macros -> {_NUMBERS}")
    print("  sources: Sextant/results/{railing_results,osipi_provenance,tcga_lihc_provenance}.json")
    print("           Gnomon/{handoff/conditional_coverage,results/reproduction}.json")


if __name__ == "__main__":
    main()
