#!/usr/bin/env python
"""CP4 consistency gate: regenerate numbers.tex from the seeded results and check.

Every number in the manuscript is a macro defined here from
``results/railing_results.json`` (and the provenance manifests) — nothing is
typed by hand. Running this script (a) re-derives the macros and (b) asserts
internal consistency; a failure aborts the paper build.
"""
from __future__ import annotations

import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
_RESULTS = os.path.join(_ROOT, "results", "railing_results.json")
_OSIPI_PROV = os.path.join(_ROOT, "results", "osipi_provenance.json")
_LIHC_PROV = os.path.join(_ROOT, "results", "tcga_lihc_provenance.json")
_MISSPEC = os.path.join(_ROOT, "results", "misspecification_isolation.json")
_PHANTOM = os.path.join(_ROOT, "results", "phantom_recovery.json")
_CRITICISM = os.path.join(_ROOT, "results", "model_criticism.json")
_NUMBERS = os.path.join(_HERE, "numbers.tex")

# cohort name -> TeX macro prefix
PREFIX = {
    "abdomen_homogeneous": "Homo",
    "abdomen_full": "Full",
    "lihc_liver_4b_0_50_500_800": "LihcFour",
    "lihc_liver_3b_50_400_800": "LihcThree",
}


def _pct(x):
    return f"{100 * x:.1f}"


def main():
    data = json.load(open(_RESULTS))
    meta = data["meta"]
    cohorts = {c["name"]: c for c in data["cohorts"]}

    lines = ["% AUTO-GENERATED by paper/consistency.py -- do not edit by hand.", ""]

    def cmd(name, val):
        lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    # meta
    cmd("seed", meta["seed"])
    cmd("nboot", f"{meta['n_boot']:,}".replace(",", "{,}"))
    cmd("thrPoint", _pct(meta["registered_thresholds"]["point_min"]))
    cmd("thrCIlo", _pct(meta["registered_thresholds"]["ci_lo_min"]))
    cmd("fashionReported", _pct(meta["fashion_reported_homogeneous"]))
    cmd("fashionN", f"{meta['fashion_reported_n_high_snr']:,}".replace(",", "{,}"))

    problems = []
    for name, c in cohorts.items():
        pre = PREFIX.get(name)
        if pre is None:
            continue
        t = c["tight"]; ci = c["bootstrap_ci"]; w = c.get("wide")
        # checks
        if not (0 <= t["frac_railed"] <= 1):
            problems.append(f"{name}: frac out of [0,1]")
        if not (ci["lo"] <= ci["point"] <= ci["hi"]):
            problems.append(f"{name}: CI does not bracket point")
        cmd(pre + "Frac", _pct(t["frac_railed"]))
        cmd(pre + "CIlo", _pct(ci["lo"]))
        cmd(pre + "CIhi", _pct(ci["hi"]))
        cmd(pre + "Lower", _pct(t["frac_lower"]))
        cmd(pre + "Upper", _pct(t["frac_upper"]))
        if w:
            cmd(pre + "Wide", _pct(w["frac_railed"]))
        cmd(pre + "N", f"{c['n_high_snr']:,}".replace(",", "{,}"))
        cmd(pre + "Verdict", c["verdict"]["label"].replace("_", "-"))
        if "n_subjects" in c:
            cmd(pre + "Subj", c["n_subjects"])

    # cross-checks
    homo = cohorts.get("abdomen_homogeneous")
    if homo and abs(homo["tight"]["frac_railed"] - meta["fashion_reported_homogeneous"]) > 0.005:
        problems.append("homogeneous railing does not match Fashion's reported 54.7%")
    if homo and homo["n_high_snr"] != meta["fashion_reported_n_high_snr"]:
        problems.append("homogeneous high-SNR count != Fashion's 1618")

    # provenance-derived macros
    if os.path.exists(_LIHC_PROV):
        lp = json.load(open(_LIHC_PROV))["dataset"]
        cmd("lihcLicense", lp["license"])
        cmd("lihcDOI", lp["doi"])
        cmd("lihcNseries", lp["n_series"])

    # --- HC2/CS2 robustness battery (Track A) macros, regenerated from results --- #
    _robustness_macros(cmd, problems, homo)

    if problems:
        print("CONSISTENCY FAILURES:")
        for p in problems:
            print("  -", p)
        sys.exit(1)

    with open(_NUMBERS, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    n_macros = sum(1 for l in lines if l.startswith("\\newcommand"))
    print(f"consistency OK: {n_macros} macros -> {_NUMBERS}")


def _robustness_macros(cmd, problems, homo):
    """Emit (and internally check) the HC2/CS2 robustness-battery macros.

    Every number in the manuscript's robustness section is regenerated here from
    results/{misspecification_isolation,phantom_recovery,model_criticism}.json so
    the consistency gate covers the Track-A additions too. Absent files are skipped
    (the gate still runs), but if present their internal invariants are checked.
    """
    def pct(x):
        return f"{100 * x:.1f}"

    if os.path.exists(_MISSPEC):
        m = json.load(open(_MISSPEC))
        cells = {(c["forward"], c["snr"]): c for c in m["cells"]}
        ws10 = cells[("biexp_WS", 10.0)]["frac_railed"]
        ws100 = cells[("biexp_WS", 100.0)]["frac_railed"]
        corner10 = cells[("biexp_WS", 10.0)]["frac_railed_hard_corner"]
        cmd("RobN", f"{m['meta']['n_truths']:,}".replace(",", "{,}"))
        cmd("RobWSrailTen", pct(ws10))
        cmd("RobWSrailHundred", pct(ws100))
        cmd("RobMaxDelta", f"{100 * m['max_abs_delta_vs_WS']:.1f}")
        cmd("RobCornerTen", pct(corner10))
        if not (0 <= m["max_abs_delta_vs_WS"] <= 1):
            problems.append("misspec max delta out of range")
        if ws10 <= 0:
            problems.append("well-specified railing is zero (isolation claim broken)")

    if os.path.exists(_PHANTOM):
        p = json.load(open(_PHANTOM))
        tis = {t["tissue"]: t for t in p["B1_brain_phantom"]["tissues"]}
        rows = p["B2_f_sweep"]["rows"]
        lo, hi = rows[0], rows[-1]               # f=0.02 (worst) .. f=0.45 (best)
        b3 = p["B3_flag_validity"]["20"]
        cmd("PhantWM", pct(tis["WM"]["frac_railed"]))
        cmd("PhantGM", pct(tis["GM"]["frac_railed"]))
        cmd("PhantSweepHiF", f"{hi['f']:.2f}")
        cmd("PhantSweepLoF", f"{lo['f']:.2f}")
        cmd("PhantSweepRailHiF", pct(hi["frac_railed"]))   # at high f -> low railing
        cmd("PhantSweepRailLoF", pct(lo["frac_railed"]))   # at low f  -> high railing
        cmd("PhantErrLoF", f"{lo['median_rel_dstar_error']:.2f}")
        cmd("PhantErrHiF", f"{hi['median_rel_dstar_error']:.2f}")
        ratio = b3["median_abs_err_railed"] / b3["median_abs_err_nonrailed"]
        cmd("PhantErrRatio", f"{ratio:.1f}")
        cmd("PhantAUC", f"{b3['auc_railed_predicts_large_error']:.2f}")
        if not (lo["frac_railed"] > hi["frac_railed"]):
            problems.append("f-sweep railing not monotone in identifiability")

    if os.path.exists(_CRITICISM):
        c = json.load(open(_CRITICISM))
        ws = c["validation"]["biexp_WS"]["flagged_frac"]
        real = c["real"]
        cmd("CritNull", pct(ws))
        cmd("CritReal", pct(real["criticised_frac"]))
        cmd("CritRailed", pct(real["criticised_frac_among_railed"]))
        cmd("CritNonRailed", pct(real["criticised_frac_among_nonrailed"]))
        # cross-check: criticism's own railing rate matches the headline 54.7%
        if homo and abs(real["frac_railed"] - homo["tight"]["frac_railed"]) > 0.02:
            problems.append("criticism railing rate != headline railing rate")
        if not (real["criticised_frac_among_railed"]
                < real["criticised_frac_among_nonrailed"]):
            problems.append("railed voxels not less-criticised than non-railed "
                            "(misspecification-isolation claim broken)")


if __name__ == "__main__":
    main()
