#!/usr/bin/env python
"""CP4 consistency gate: regenerate numbers.tex from the seeded results and check.

Every number in the manuscript is a macro defined here from
``results/railing_results.json`` (and the provenance manifests) — nothing is
typed by hand. Running this script (a) re-derives the macros and (b) asserts
internal consistency; a failure aborts the paper build.
"""
from __future__ import annotations

import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
_RESULTS = os.path.join(_ROOT, "results", "railing_results.json")
_OSIPI_PROV = os.path.join(_ROOT, "results", "osipi_provenance.json")
_LIHC_PROV = os.path.join(_ROOT, "results", "tcga_lihc_provenance.json")
_NUMBERS = os.path.join(_HERE, "numbers.tex")

# cohort name -> TeX macro prefix
PREFIX = {
    "abdomen_homogeneous": "Homo",
    "abdomen_full": "Full",
    "lihc_liver_4b_0_50_500_800": "LihcFour",
    "lihc_liver_3b_50_400_800": "LihcThree",
}


def _pct(x):
    return f"{100 * x:.1f}"


def main():
    data = json.load(open(_RESULTS))
    meta = data["meta"]
    cohorts = {c["name"]: c for c in data["cohorts"]}

    lines = ["% AUTO-GENERATED by paper/consistency.py -- do not edit by hand.", ""]

    def cmd(name, val):
        lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    # meta
    cmd("seed", meta["seed"])
    cmd("nboot", f"{meta['n_boot']:,}".replace(",", "{,}"))
    cmd("thrPoint", _pct(meta["registered_thresholds"]["point_min"]))
    cmd("thrCIlo", _pct(meta["registered_thresholds"]["ci_lo_min"]))
    cmd("fashionReported", _pct(meta["fashion_reported_homogeneous"]))
    cmd("fashionN", f"{meta['fashion_reported_n_high_snr']:,}".replace(",", "{,}"))

    problems = []
    for name, c in cohorts.items():
        pre = PREFIX.get(name)
        if pre is None:
            continue
        t = c["tight"]; ci = c["bootstrap_ci"]; w = c.get("wide")
        # checks
        if not (0 <= t["frac_railed"] <= 1):
            problems.append(f"{name}: frac out of [0,1]")
        if not (ci["lo"] <= ci["point"] <= ci["hi"]):
            problems.append(f"{name}: CI does not bracket point")
        cmd(pre + "Frac", _pct(t["frac_railed"]))
        cmd(pre + "CIlo", _pct(ci["lo"]))
        cmd(pre + "CIhi", _pct(ci["hi"]))
        cmd(pre + "Lower", _pct(t["frac_lower"]))
        cmd(pre + "Upper", _pct(t["frac_upper"]))
        if w:
            cmd(pre + "Wide", _pct(w["frac_railed"]))
        cmd(pre + "N", f"{c['n_high_snr']:,}".replace(",", "{,}"))
        cmd(pre + "Verdict", c["verdict"]["label"].replace("_", "-"))
        if "n_subjects" in c:
            cmd(pre + "Subj", c["n_subjects"])

    # cross-checks
    homo = cohorts.get("abdomen_homogeneous")
    if homo and abs(homo["tight"]["frac_railed"] - meta["fashion_reported_homogeneous"]) > 0.005:
        problems.append("homogeneous railing does not match Fashion's reported 54.7%")
    if homo and homo["n_high_snr"] != meta["fashion_reported_n_high_snr"]:
        problems.append("homogeneous high-SNR count != Fashion's 1618")

    # provenance-derived macros
    if os.path.exists(_LIHC_PROV):
        lp = json.load(open(_LIHC_PROV))["dataset"]
        cmd("lihcLicense", lp["license"])
        cmd("lihcDOI", lp["doi"])
        cmd("lihcNseries", lp["n_series"])

    with open(_NUMBERS, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    if problems:
        print("CONSISTENCY FAILURES:")
        for p in problems:
            print("  -", p)
        sys.exit(1)
    n_macros = sum(1 for l in lines if l.startswith("\\newcommand"))
    print(f"consistency OK: {n_macros} macros -> {_NUMBERS}")


if __name__ == "__main__":
    main()
